---
kind: pipeline
name: test_and_build
steps:
- commands:
  - git fetch --tags
  image: alpine/git
  name: fetch
- commands:
  - ./scripts/go-test.sh
  environment:
    GOPROXY: http://goproxy
  image: publicawesome/golang:1.22.7-devtooling
  name: test
- commands:
  - apk add --no-cache ca-certificates build-base git
  - wget https://github.com/CosmWasm/wasmvm/releases/download/v2.2.1/libwasmvm_muslc.x86_64.a
    -O /lib/libwasmvm_muslc.x86_64.a
  - echo 'b3bd755efac0ff39c01b59b8110f961c48aa3eb93588071d7a628270cc1f2326  /lib/libwasmvm_muslc.x86_64.a'
    | sha256sum -c
  - LEDGER_ENABLED=false BUILD_TAGS=muslc LINK_STATICALLY=true  make build
  - echo 'Ensuring binary is statically linked ...' && (file $PWD/bin/starsd | grep
    'statically linked')
  environment:
    GOPROXY: http://goproxy
  image: golang:1.22.7-alpine3.19
  name: build
type: docker
