---
kind: pipeline
name: test_and_build
services:
- image: docker:dind
  name: dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
steps:
- commands:
  - git fetch --tags
  image: alpine/git
  name: fetch
- commands:
  - ls -l /var/run/docker.sock
  - test -S /var/run/docker.sock && echo 'Docker socket found' || echo 'Docker socket
    missing'
  image: alpine
  name: debug_dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- commands:
  - ./scripts/go-test.sh
  environment:
    GOPROXY: http://goproxy
  image: publicawesome/golang:1.23.5-devtooling
  name: test
- commands:
  - apk add --no-cache ca-certificates build-base git
  - wget https://github.com/CosmWasm/wasmvm/releases/download/v2.1.4/libwasmvm_muslc.x86_64.a
    -O /lib/libwasmvm_muslc.x86_64.a
  - echo 'a4a3d09b36fabb65b119d5ba23442c23694401fcbee4451fe6b7e22e325a4bac /lib/libwasmvm_muslc.x86_64.a'
    | sha256sum -c
  - LEDGER_ENABLED=false BUILD_TAGS=muslc LINK_STATICALLY=true  make build
  - echo 'Ensuring binary is statically linked ...' && (file $PWD/bin/starsd | grep
    'statically linked')
  environment:
    GOPROXY: http://goproxy
  image: golang:1.23.5-alpine3.20
  name: build
- commands:
  - docker build -t publicawesome/stargaze:latest .
  image: docker:24
  name: build_docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
type: docker
volumes:
- name: dockersock
  path: /var/run/docker.sock
