---
kind: pipeline
type: docker
name: default-build

workspace:
  path: /stargaze

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
  - name: restore-cache
    image: meltwater/drone-cache:dev
    volumes:
      - name: cache
        path: /go
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: minio_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: minio_secret_key
    pull: always
    settings:
      restore: true
      bucket:
        from_secret: minio_bucket
      region: us-east-1
      mount:
        - '/go/pkg/mod'
    when:
      branch: no-cache

  - name: test
    image: publicawesome/golang:1.21.3-devtooling
    volumes:
      - name: cache
        path: /go
    commands:
      - ./scripts/go-test.sh
    environment:
      GOPROXY: http://goproxy
  - name: build
    image: golang:1.21.3-alpine3.17
    volumes:
      - name: cache
        path: /go
    commands:
      - apk add --no-cache ca-certificates build-base git
      - wget https://github.com/CosmWasm/wasmvm/releases/download/v1.5.2/libwasmvm_muslc.x86_64.a -O /lib/libwasmvm_muslc.a
      - echo "e660a38efb2930b34ee6f6b0bb12730adccb040b6ab701b8f82f34453a426ae7  /lib/libwasmvm_muslc.a" | sha256sum -c
      - LEDGER_ENABLED=false BUILD_TAGS=muslc LINK_STATICALLY=true  make build
      - echo "Ensuring binary is statically linked ..." && (file $PWD/bin/starsd | grep "statically linked")
    environment:
      GOPROXY: http://goproxy
  - name: coverage
    image: plugins/codecov
    volumes:
      - name: cache
        path: /go
    settings:
      required: true
      token:
        from_secret: codecov-token
    when:
      event:
        - push
        - pull_request
  - name: publish-alpha
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile
      repo: publicawesome/stargaze
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - 13.0.0-beta.1
    when:
      event:
        - push
      branch:
        - jhernandezb/prepare-v12-beta
  - name: docker_release
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile
      repo: publicawesome/stargaze
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
    when:
      event:
        - tag

  - name: release
    image: golang:1.21.3
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - curl -sL https://git.io/goreleaser | bash
    environment:
      GOPROXY: http://goproxy
    when:
      event:
        - tag
  - name: rebuild-cache
    image: meltwater/drone-cache:dev
    volumes:
      - name: cache
        path: /go
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: minio_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: minio_secret_key
    pull: always
    settings:
      rebuild: true
      bucket:
        from_secret: minio_bucket
      region: us-east-1
      mount:
        - '/go/pkg/mod'
    when:
      branch: no-cache
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
    when:
      status: [success, failure]

volumes:
- name: cache
  temp: {}
---
kind: pipeline
type: docker
name: ibc-integration-test

steps:
  - name: restore-cache
    image: meltwater/drone-cache:dev
    volumes:
      - name: cache
        path: /go
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: minio_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: minio_secret_key
    pull: always
    settings:
      restore: true
      bucket:
        from_secret: minio_bucket
      region: us-east-1
      mount:
        - '/go/pkg/mod'
    when:
      branch: no-cache
  - name: gaia
    image: publicawesome/gaia:7.0.2
    detach: true
    commands:
      - ./scripts/ci/setup-gaia.sh
    environment:
      GOPROXY: http://goproxy
  - name: osmosis
    image: publicawesome/osmosis:10.1.1
    detach: true
    commands:
      - ./scripts/ci/setup-osmosis.sh
    environment:
      GOPROXY: http://goproxy
  - name: icad
    image: publicawesome/icad:0.1.6-stargaze.1
    pull: always
    detach: true
    commands:
      - echo $PWD
      - ls -ltrah
      - ./scripts/ci/setup-icad.sh
    environment:
      GOPROXY: http://goproxy
  - name: stargaze
    image: publicawesome/golang:1.21.3-devtooling
    volumes:
      - name: cache
        path: /go
    commands:
      - ./scripts/ci/setup-stargaze.sh
    environment:
      GOPROXY: http://goproxy
    detach: true
  - name: readiness
    pull: always
    image: publicawesome/stargaze-readiness-checker:latest
    settings:
      timeout: 300
      blocks: 10
      chain_list:
        - http://stargaze:26657
        - http://gaia:26657
        - http://osmosis:26657
        - http://icad:26657
  - name: relayer
    image: publicawesome/hermes:1.7.3
    commands:
      - /bin/bash ./scripts/ci/setup-hermes-1.7.sh

  - name: relayer-start
    image: publicawesome/hermes:1.7.3
    commands:
      - /bin/bash ./scripts/ci/start-relayer-v1.7.sh
    detach: true
  - name: relayer-sender
    image: publicawesome/hermes:1.7.3
    commands:
      - /bin/bash ./scripts/ci/transfer-relayer-v1.7.sh
  - name: ica-test
    image: publicawesome/icad:0.1.6-stargaze.1
    pull: always
    commands:
      - /bin/sh ./scripts/ci/test-ica.sh
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
    when:
      status: [success, failure]

trigger:
  branch:
    - main
  event:
    - pull_request
    - push
volumes:
- name: cache
  temp: {}

---
kind: pipeline
type: docker
name: upgrade-integration-test
workspace:
  path: /stargaze
steps:
  - name: restore-cache
    image: meltwater/drone-cache:dev
    volumes:
      - name: cache
        path: /go
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: minio_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: minio_secret_key
    pull: always
    settings:
      restore: true
      bucket:
        from_secret: minio_bucket
      region: us-east-1
      mount:
        - '/go/pkg/mod'
    when:
      branch: no-cache
  - name: build-wrapper
    image: publicawesome/golang:1.21.3-devtooling
    volumes:
      - name: cache
        path: /go
    commands:
      - mkdir -p /stargaze/bin/
      - CGO_ENABLED=0 go build -o /stargaze/bin/upgrade-watcher ./testutil/watcher/
      - chmod +x /stargaze/bin/upgrade-watcher
    environment:
      GOPROXY: http://goproxy
  - name: gaia
    image: publicawesome/gaia:7.0.2
    detach: true
    commands:
      - ./scripts/ci/setup-gaia.sh
    environment:
      GOPROXY: http://goproxy
  - name: osmosis
    image: publicawesome/osmosis:10.1.1
    detach: true
    commands:
      - ./scripts/ci/setup-osmosis.sh
    environment:
      GOPROXY: http://goproxy
  - name: icad
    image: publicawesome/icad:0.1.6-stargaze.1
    pull: always
    detach: true
    commands:
      - ./scripts/ci/setup-icad.sh
    environment:
      GOPROXY: http://goproxy
  - name: stargaze
    image: publicawesome/stargaze:12.0.0
    commands:
      - ./scripts/ci/upgrade/setup-preinstalled-stargaze.sh
    environment:
      GOPROXY: http://goproxy
    detach: true
  - name: readiness
    pull: always
    image: publicawesome/stargaze-readiness-checker:latest
    settings:
      timeout: 300
      blocks: 10
      chain_list:
        - http://stargaze:26657
        - http://gaia:26657
        - http://osmosis:26657
        - http://icad:26657
  - name: relayer
    image: publicawesome/hermes:0.15.0
    commands:
      - /bin/bash ./scripts/ci/setup-relayer.sh

  - name: relayer-start
    image: publicawesome/hermes:0.15.0
    commands:
      - /bin/bash ./scripts/ci/start-relayer.sh
    detach: true
  - name: relayer-sender
    image: publicawesome/hermes:0.15.0
    commands:
      - /bin/bash ./scripts/ci/transfer-relayer.sh
  - name: proposal
    image: publicawesome/stargaze:12.1.0
    commands:
      - ./scripts/ci/upgrade/proposal.sh
  - name: stargaze-upgraded
    pull: always
    image: publicawesome/stargaze:13.0.0-beta.1
    commands:
      - ./scripts/ci/upgrade/run-upgrade.sh
    environment:
      GOPROXY: http://goproxy
    detach: true
  - name: readiness-upgrade
    pull: always
    image: publicawesome/stargaze-readiness-checker:latest
    settings:
      timeout: 300
      blocks: 10
      chain_list:
        - http://stargaze-upgraded:26657
        - http://gaia:26657
        - http://osmosis:26657
        - http://icad:26657
  - name: check-params
    pull: always
    image: publicawesome/stargaze:13.0.0-beta.1
    commands:
      - starsd q mint params --node http://stargaze-upgraded:26657
      - starsd q alloc params --node http://stargaze-upgraded:26657
      - starsd q tokenfactory params --node http://stargaze-upgraded:26657
      - starsd q bank balances stars1mnyrspq208uv5m2krdctan2dkyht0szje9s43h --node http://stargaze-upgraded:26657
      - starsd q bank balances stars103y4f6h80lc45nr8chuzr3fyzqywm9n0gnr394 --node http://stargaze-upgraded:26657
      - starsd q distribution community-pool --node http://stargaze-upgraded:26657
      - starsd q interchain-accounts host params --node http://stargaze-upgraded:26657
    environment:
      GOPROXY: http://goproxy
  - name: relayer-upgrade-start
    image: publicawesome/hermes:1.7.3
    commands:
      - /bin/bash ./scripts/ci/upgrade/start-relayer-v1.7.sh
    detach: true
  - name: relayer-upgrade-sender
    image: publicawesome/hermes:1.7.3
    commands:
      - /bin/bash ./scripts/ci/upgrade/transfer-relayer-v1.7.sh
  - name: ica-upgrade-test
    image: publicawesome/icad:0.1.6-stargaze.1
    pull: always
    commands:
      - /bin/sh ./scripts/ci/upgrade/test-ica.sh
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
    when:
      status: [success, failure]

trigger:
  branch:
    - main
  event:
    - pull_request
    - push
depends_on:
  - ibc-integration-test
volumes:
- name: cache
  temp: {}


---
kind: signature
hmac: 09100358e827f91073cee9dbfd1bb3e87a604d378f21f0899bacdb67606de3c5

...
