version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
  settings:
    dogsled:
      max-blank-identifiers: 3
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
    revive:
      rules:
        - name: var-naming
          disabled: true
    staticcheck:
      checks:
        - all
        - -QF1007
        - -QF1008
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: Use of weak random number generator
      - linters:
          - golint
        text: comment on exported var
      - linters:
          - golint
        text: don't use an underscore in package name
      - linters:
          - staticcheck
        text: 'ST1003:'
      - linters:
          - staticcheck
        text: 'ST1016:'
      - linters:
          - staticcheck
        path: legacy
        text: 'SA1019:'
    paths:
      - simapp
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - simapp
      - third_party$
      - builtin$
      - examples$
