queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>1"

pull_request_rules:
  - name: automerge to main if approved and labeled
    conditions:
      - "#approved-reviews-by>1"
      - base=main
      - label=automerge
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          {{ body }}
  - name: backport to v8
    conditions:
      - base=main
      - label=backport/8.x
    actions:
      backport:
        branches:
          - release/v8.x
  - name: backport to v7
    conditions:
      - base=main
      - label=backport/7.x
    actions:
      backport:
        branches:
          - release/v7.x
  - name: backport to v6
    conditions:
      - base=main
      - label=backport/6.x
    actions:
      backport:
        branches:
          - release/v6.x
  - name: backport to v5
    conditions:
      - base=main
      - label=backport/5.x
    actions:
      backport:
        branches:
          - release/v5.x
  - name: backport to v4
    conditions:
      - base=main
      - label=backport/4.x
    actions:
      backport:
        branches:
          - release/v4.x
  - name: backport to v3
    conditions:
      - base=main
      - label=backport/3.x
    actions:
      backport:
        branches:
          - release/v3.x
  - name: backport to v2
    conditions:
      - base=main
      - label=backport/2.x
    actions:
      backport:
        branches:
          - release/v2.x
  - name: backport to v1
    conditions:
      - base=main
      - label=backport/1.x
    actions:
      backport:
        branches:
          - release/v1.x
