queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>1"
      - base=main
      - label=automerge
    merge_conditions:
      - "#approved-reviews-by>1"
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: backport to v13
    conditions:
      - base=main
      - label=backport/v13.x
    actions:
      backport:
        branches:
          - release/v13.x
  - name: backport to v12
    conditions:
      - base=main
      - label=backport/v12.x
    actions:
      backport:
        branches:
          - release/v12.x
  - name: backport to v11
    conditions:
      - base=main
      - label=backport/v11.x
    actions:
      backport:
        branches:
          - release/v11.x
  - name: backport to v10
    conditions:
      - base=main
      - label=backport/v10.x
    actions:
      backport:
        branches:
          - release/v10.x
  - name: backport to v9
    conditions:
      - base=main
      - label=backport/9.x
    actions:
      backport:
        branches:
          - release/v9.x
  - name: backport to v8
    conditions:
      - base=main
      - label=backport/8.x
    actions:
      backport:
        branches:
          - release/v8.x
  - name: backport to v7
    conditions:
      - base=main
      - label=backport/7.x
    actions:
      backport:
        branches:
          - release/v7.x
  - name: backport to v6
    conditions:
      - base=main
      - label=backport/6.x
    actions:
      backport:
        branches:
          - release/v6.x
  - name: backport to v5
    conditions:
      - base=main
      - label=backport/5.x
    actions:
      backport:
        branches:
          - release/v5.x
  - name: backport to v4
    conditions:
      - base=main
      - label=backport/4.x
    actions:
      backport:
        branches:
          - release/v4.x
  - name: backport to v3
    conditions:
      - base=main
      - label=backport/3.x
    actions:
      backport:
        branches:
          - release/v3.x
  - name: backport to v2
    conditions:
      - base=main
      - label=backport/2.x
    actions:
      backport:
        branches:
          - release/v2.x
  - name: backport to v1
    conditions:
      - base=main
      - label=backport/1.x
    actions:
      backport:
        branches:
          - release/v1.x
  - name: automerge to main if approved and labeled
    conditions: []
    actions:
      queue:
