// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: publicawesome/stargaze/globalfee/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryCodeAuthorizationRequest struct {
	CodeId uint64 `protobuf:"varint,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
}

func (m *QueryCodeAuthorizationRequest) Reset()         { *m = QueryCodeAuthorizationRequest{} }
func (m *QueryCodeAuthorizationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCodeAuthorizationRequest) ProtoMessage()    {}
func (*QueryCodeAuthorizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fbf6368ed5b177, []int{0}
}
func (m *QueryCodeAuthorizationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCodeAuthorizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCodeAuthorizationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCodeAuthorizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCodeAuthorizationRequest.Merge(m, src)
}
func (m *QueryCodeAuthorizationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCodeAuthorizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCodeAuthorizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCodeAuthorizationRequest proto.InternalMessageInfo

func (m *QueryCodeAuthorizationRequest) GetCodeId() uint64 {
	if m != nil {
		return m.CodeId
	}
	return 0
}

type QueryCodeAuthorizationResponse struct {
	Methods []string `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (m *QueryCodeAuthorizationResponse) Reset()         { *m = QueryCodeAuthorizationResponse{} }
func (m *QueryCodeAuthorizationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCodeAuthorizationResponse) ProtoMessage()    {}
func (*QueryCodeAuthorizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fbf6368ed5b177, []int{1}
}
func (m *QueryCodeAuthorizationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCodeAuthorizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCodeAuthorizationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCodeAuthorizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCodeAuthorizationResponse.Merge(m, src)
}
func (m *QueryCodeAuthorizationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCodeAuthorizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCodeAuthorizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCodeAuthorizationResponse proto.InternalMessageInfo

func (m *QueryCodeAuthorizationResponse) GetMethods() []string {
	if m != nil {
		return m.Methods
	}
	return nil
}

type QueryContractAuthorizationRequest struct {
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
}

func (m *QueryContractAuthorizationRequest) Reset()         { *m = QueryContractAuthorizationRequest{} }
func (m *QueryContractAuthorizationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryContractAuthorizationRequest) ProtoMessage()    {}
func (*QueryContractAuthorizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fbf6368ed5b177, []int{2}
}
func (m *QueryContractAuthorizationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryContractAuthorizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryContractAuthorizationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryContractAuthorizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContractAuthorizationRequest.Merge(m, src)
}
func (m *QueryContractAuthorizationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryContractAuthorizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContractAuthorizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContractAuthorizationRequest proto.InternalMessageInfo

func (m *QueryContractAuthorizationRequest) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

type QueryContractAuthorizationResponse struct {
	Methods []string `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (m *QueryContractAuthorizationResponse) Reset()         { *m = QueryContractAuthorizationResponse{} }
func (m *QueryContractAuthorizationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryContractAuthorizationResponse) ProtoMessage()    {}
func (*QueryContractAuthorizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fbf6368ed5b177, []int{3}
}
func (m *QueryContractAuthorizationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryContractAuthorizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryContractAuthorizationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryContractAuthorizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContractAuthorizationResponse.Merge(m, src)
}
func (m *QueryContractAuthorizationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryContractAuthorizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContractAuthorizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContractAuthorizationResponse proto.InternalMessageInfo

func (m *QueryContractAuthorizationResponse) GetMethods() []string {
	if m != nil {
		return m.Methods
	}
	return nil
}

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fbf6368ed5b177, []int{4}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fbf6368ed5b177, []int{5}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type QueryAuthorizationsRequest struct {
}

func (m *QueryAuthorizationsRequest) Reset()         { *m = QueryAuthorizationsRequest{} }
func (m *QueryAuthorizationsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAuthorizationsRequest) ProtoMessage()    {}
func (*QueryAuthorizationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fbf6368ed5b177, []int{6}
}
func (m *QueryAuthorizationsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuthorizationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuthorizationsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuthorizationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuthorizationsRequest.Merge(m, src)
}
func (m *QueryAuthorizationsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuthorizationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuthorizationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuthorizationsRequest proto.InternalMessageInfo

type QueryAuthorizationsResponse struct {
	CodeAuthorizations     []*CodeAuthorization     `protobuf:"bytes,1,rep,name=code_authorizations,json=codeAuthorizations,proto3" json:"code_authorizations,omitempty"`
	ContractAuthorizations []*ContractAuthorization `protobuf:"bytes,2,rep,name=contract_authorizations,json=contractAuthorizations,proto3" json:"contract_authorizations,omitempty"`
}

func (m *QueryAuthorizationsResponse) Reset()         { *m = QueryAuthorizationsResponse{} }
func (m *QueryAuthorizationsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAuthorizationsResponse) ProtoMessage()    {}
func (*QueryAuthorizationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fbf6368ed5b177, []int{7}
}
func (m *QueryAuthorizationsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuthorizationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuthorizationsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuthorizationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuthorizationsResponse.Merge(m, src)
}
func (m *QueryAuthorizationsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuthorizationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuthorizationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuthorizationsResponse proto.InternalMessageInfo

func (m *QueryAuthorizationsResponse) GetCodeAuthorizations() []*CodeAuthorization {
	if m != nil {
		return m.CodeAuthorizations
	}
	return nil
}

func (m *QueryAuthorizationsResponse) GetContractAuthorizations() []*ContractAuthorization {
	if m != nil {
		return m.ContractAuthorizations
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryCodeAuthorizationRequest)(nil), "publicawesome.stargaze.globalfee.v1.QueryCodeAuthorizationRequest")
	proto.RegisterType((*QueryCodeAuthorizationResponse)(nil), "publicawesome.stargaze.globalfee.v1.QueryCodeAuthorizationResponse")
	proto.RegisterType((*QueryContractAuthorizationRequest)(nil), "publicawesome.stargaze.globalfee.v1.QueryContractAuthorizationRequest")
	proto.RegisterType((*QueryContractAuthorizationResponse)(nil), "publicawesome.stargaze.globalfee.v1.QueryContractAuthorizationResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "publicawesome.stargaze.globalfee.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "publicawesome.stargaze.globalfee.v1.QueryParamsResponse")
	proto.RegisterType((*QueryAuthorizationsRequest)(nil), "publicawesome.stargaze.globalfee.v1.QueryAuthorizationsRequest")
	proto.RegisterType((*QueryAuthorizationsResponse)(nil), "publicawesome.stargaze.globalfee.v1.QueryAuthorizationsResponse")
}

func init() {
	proto.RegisterFile("publicawesome/stargaze/globalfee/v1/query.proto", fileDescriptor_28fbf6368ed5b177)
}

var fileDescriptor_28fbf6368ed5b177 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0xae, 0x07, 0x74, 0xda, 0x3b, 0x89, 0x0f, 0x0f, 0x58, 0x15, 0xb6, 0x30, 0x82, 0x26, 0x86,
	0xd0, 0x12, 0xb5, 0x15, 0x50, 0x0d, 0x09, 0xb6, 0x56, 0xe2, 0xe3, 0x82, 0x20, 0xc7, 0x5d, 0x26,
	0x37, 0x31, 0x69, 0xa4, 0x36, 0xce, 0x62, 0xa7, 0xb0, 0xa1, 0x5d, 0xf8, 0x05, 0x48, 0xfc, 0x03,
	0x7e, 0xca, 0x4e, 0x1c, 0x27, 0x71, 0x81, 0x1b, 0x6a, 0xf9, 0x05, 0x5c, 0xb9, 0xa0, 0x3a, 0xee,
	0x46, 0xd6, 0x64, 0x64, 0xec, 0x98, 0xd7, 0x7a, 0xbe, 0xf2, 0xfa, 0x91, 0xc1, 0x0a, 0xe3, 0x76,
	0xd7, 0x77, 0xc8, 0x5b, 0xca, 0x59, 0x8f, 0x5a, 0x5c, 0x90, 0xc8, 0x23, 0xbb, 0xd4, 0xf2, 0xba,
	0xac, 0x4d, 0xba, 0x6f, 0x28, 0xb5, 0xfa, 0x55, 0x6b, 0x3b, 0xa6, 0xd1, 0x8e, 0x19, 0x46, 0x4c,
	0x30, 0x7c, 0x3b, 0x05, 0x30, 0xc7, 0x00, 0xf3, 0x10, 0x60, 0xf6, 0xab, 0xda, 0x82, 0xc7, 0x98,
	0xd7, 0xa5, 0x16, 0x09, 0x7d, 0x8b, 0x04, 0x01, 0x13, 0x44, 0xf8, 0x2c, 0xe0, 0x09, 0x85, 0x56,
	0x2f, 0xa2, 0x79, 0xc4, 0x27, 0x41, 0x46, 0x03, 0x16, 0x5f, 0x8f, 0x6c, 0xb4, 0x98, 0x4b, 0x37,
	0x62, 0xd1, 0x61, 0x91, 0xbf, 0x2b, 0x59, 0x6d, 0xba, 0x1d, 0x53, 0x2e, 0xf0, 0x3c, 0x4c, 0x3b,
	0xcc, 0xa5, 0x5b, 0xbe, 0x5b, 0x41, 0x4b, 0x68, 0xe5, 0xbc, 0x5d, 0x1e, 0x7d, 0xbe, 0x70, 0x8d,
	0x35, 0xd0, 0xf3, 0x90, 0x3c, 0x64, 0x01, 0xa7, 0xb8, 0x02, 0xd3, 0x3d, 0x2a, 0x3a, 0xcc, 0xe5,
	0x15, 0xb4, 0x74, 0x6e, 0x65, 0xc6, 0x1e, 0x7f, 0x1a, 0x2f, 0xe1, 0x96, 0xc2, 0x06, 0x22, 0x22,
	0x8e, 0xc8, 0x54, 0xbe, 0x0b, 0x97, 0x1d, 0x75, 0xbe, 0x45, 0x5c, 0x37, 0xa2, 0x9c, 0x4b, 0x0b,
	0x33, 0xf6, 0xa5, 0xf1, 0x7c, 0x23, 0x19, 0x1b, 0x8f, 0xc1, 0x38, 0x89, 0xef, 0x9f, 0x7e, 0xae,
	0x02, 0x96, 0xf8, 0x57, 0x24, 0x22, 0x3d, 0xae, 0x0c, 0x18, 0x9b, 0x30, 0x97, 0x9a, 0x2a, 0x9a,
	0x16, 0x94, 0x43, 0x39, 0x91, 0x6e, 0x66, 0x6b, 0xf7, 0xcc, 0x02, 0xbb, 0x33, 0x15, 0x89, 0x82,
	0x1a, 0x0b, 0xa0, 0x49, 0xee, 0x94, 0xd3, 0x43, 0xe5, 0xdf, 0x08, 0x6e, 0x64, 0x1e, 0x2b, 0x0b,
	0x1e, 0xcc, 0xc9, 0xa5, 0x90, 0xd4, 0xb1, 0x4c, 0x35, 0x5b, 0x7b, 0x50, 0xc8, 0xcf, 0xe4, 0xda,
	0xb0, 0x73, 0x7c, 0xc4, 0x31, 0x87, 0xf9, 0xa3, 0x1d, 0xa4, 0xc5, 0xa6, 0xa4, 0xd8, 0x5a, 0x41,
	0xb1, 0xac, 0xbd, 0x5c, 0x77, 0xb2, 0xc6, 0xbc, 0xb6, 0x5f, 0x86, 0x0b, 0x32, 0x3d, 0xfe, 0x8e,
	0xe0, 0xca, 0x84, 0x51, 0xdc, 0x2c, 0xa4, 0x79, 0xe2, 0xb5, 0xd6, 0x5a, 0x67, 0xe2, 0x48, 0xd6,
	0x60, 0x3c, 0xfa, 0xf0, 0xf5, 0xe7, 0xa7, 0xa9, 0xfb, 0xb8, 0x9e, 0x53, 0xb6, 0xc9, 0x1d, 0x59,
	0xef, 0x55, 0x99, 0xf6, 0xf0, 0x2f, 0x04, 0xd7, 0x32, 0xff, 0x0b, 0x7e, 0x7a, 0x1a, 0x6f, 0xf9,
	0x05, 0xd2, 0x9e, 0x9d, 0x99, 0x47, 0xe5, 0x7c, 0x2e, 0x73, 0x36, 0xf1, 0x7a, 0x6e, 0xce, 0xac,
	0x2b, 0x32, 0xca, 0x9a, 0xae, 0xef, 0x1e, 0xfe, 0x8c, 0xa0, 0x9c, 0x34, 0x01, 0x3f, 0x2c, 0xee,
	0x2e, 0x55, 0x4b, 0xad, 0x71, 0x7a, 0xa0, 0xca, 0xb1, 0x2c, 0x73, 0xdc, 0xc4, 0x8b, 0x39, 0x39,
	0x92, 0x6e, 0xe2, 0x7d, 0x04, 0x17, 0x8f, 0xf5, 0xe0, 0x49, 0x71, 0xcd, 0xcc, 0x46, 0x6b, 0xeb,
	0xff, 0x4f, 0xa0, 0xcc, 0xaf, 0x4a, 0xf3, 0x77, 0xf0, 0x72, 0x8e, 0xf9, 0x74, 0x3d, 0x9b, 0xf6,
	0x97, 0x81, 0x8e, 0x0e, 0x06, 0x3a, 0xfa, 0x31, 0xd0, 0xd1, 0xc7, 0xa1, 0x5e, 0x3a, 0x18, 0xea,
	0xa5, 0x6f, 0x43, 0xbd, 0xb4, 0xd9, 0xf0, 0x7c, 0xd1, 0x89, 0xdb, 0xa6, 0xc3, 0x7a, 0xea, 0x99,
	0x5a, 0x9d, 0x78, 0x33, 0xfa, 0xd5, 0x9a, 0xf5, 0xee, 0x2f, 0x7e, 0xb1, 0x13, 0x52, 0xde, 0x2e,
	0xcb, 0x37, 0xa3, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x68, 0x27, 0x32, 0xde, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	CodeAuthorization(ctx context.Context, in *QueryCodeAuthorizationRequest, opts ...grpc.CallOption) (*QueryCodeAuthorizationResponse, error)
	ContractAuthorization(ctx context.Context, in *QueryContractAuthorizationRequest, opts ...grpc.CallOption) (*QueryContractAuthorizationResponse, error)
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	Authorizations(ctx context.Context, in *QueryAuthorizationsRequest, opts ...grpc.CallOption) (*QueryAuthorizationsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) CodeAuthorization(ctx context.Context, in *QueryCodeAuthorizationRequest, opts ...grpc.CallOption) (*QueryCodeAuthorizationResponse, error) {
	out := new(QueryCodeAuthorizationResponse)
	err := c.cc.Invoke(ctx, "/publicawesome.stargaze.globalfee.v1.Query/CodeAuthorization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ContractAuthorization(ctx context.Context, in *QueryContractAuthorizationRequest, opts ...grpc.CallOption) (*QueryContractAuthorizationResponse, error) {
	out := new(QueryContractAuthorizationResponse)
	err := c.cc.Invoke(ctx, "/publicawesome.stargaze.globalfee.v1.Query/ContractAuthorization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/publicawesome.stargaze.globalfee.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Authorizations(ctx context.Context, in *QueryAuthorizationsRequest, opts ...grpc.CallOption) (*QueryAuthorizationsResponse, error) {
	out := new(QueryAuthorizationsResponse)
	err := c.cc.Invoke(ctx, "/publicawesome.stargaze.globalfee.v1.Query/Authorizations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	CodeAuthorization(context.Context, *QueryCodeAuthorizationRequest) (*QueryCodeAuthorizationResponse, error)
	ContractAuthorization(context.Context, *QueryContractAuthorizationRequest) (*QueryContractAuthorizationResponse, error)
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	Authorizations(context.Context, *QueryAuthorizationsRequest) (*QueryAuthorizationsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) CodeAuthorization(ctx context.Context, req *QueryCodeAuthorizationRequest) (*QueryCodeAuthorizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CodeAuthorization not implemented")
}
func (*UnimplementedQueryServer) ContractAuthorization(ctx context.Context, req *QueryContractAuthorizationRequest) (*QueryContractAuthorizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContractAuthorization not implemented")
}
func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Authorizations(ctx context.Context, req *QueryAuthorizationsRequest) (*QueryAuthorizationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authorizations not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_CodeAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCodeAuthorizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CodeAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publicawesome.stargaze.globalfee.v1.Query/CodeAuthorization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CodeAuthorization(ctx, req.(*QueryCodeAuthorizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ContractAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryContractAuthorizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ContractAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publicawesome.stargaze.globalfee.v1.Query/ContractAuthorization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ContractAuthorization(ctx, req.(*QueryContractAuthorizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publicawesome.stargaze.globalfee.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Authorizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuthorizationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Authorizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publicawesome.stargaze.globalfee.v1.Query/Authorizations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Authorizations(ctx, req.(*QueryAuthorizationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "publicawesome.stargaze.globalfee.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CodeAuthorization",
			Handler:    _Query_CodeAuthorization_Handler,
		},
		{
			MethodName: "ContractAuthorization",
			Handler:    _Query_ContractAuthorization_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Authorizations",
			Handler:    _Query_Authorizations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "publicawesome/stargaze/globalfee/v1/query.proto",
}

func (m *QueryCodeAuthorizationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCodeAuthorizationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCodeAuthorizationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CodeId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CodeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryCodeAuthorizationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCodeAuthorizationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCodeAuthorizationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Methods) > 0 {
		for iNdEx := len(m.Methods) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Methods[iNdEx])
			copy(dAtA[i:], m.Methods[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Methods[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryContractAuthorizationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryContractAuthorizationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryContractAuthorizationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryContractAuthorizationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryContractAuthorizationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryContractAuthorizationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Methods) > 0 {
		for iNdEx := len(m.Methods) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Methods[iNdEx])
			copy(dAtA[i:], m.Methods[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Methods[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAuthorizationsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuthorizationsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuthorizationsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAuthorizationsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuthorizationsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuthorizationsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractAuthorizations) > 0 {
		for iNdEx := len(m.ContractAuthorizations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ContractAuthorizations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.CodeAuthorizations) > 0 {
		for iNdEx := len(m.CodeAuthorizations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CodeAuthorizations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryCodeAuthorizationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CodeId != 0 {
		n += 1 + sovQuery(uint64(m.CodeId))
	}
	return n
}

func (m *QueryCodeAuthorizationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Methods) > 0 {
		for _, s := range m.Methods {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryContractAuthorizationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryContractAuthorizationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Methods) > 0 {
		for _, s := range m.Methods {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAuthorizationsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAuthorizationsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CodeAuthorizations) > 0 {
		for _, e := range m.CodeAuthorizations {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.ContractAuthorizations) > 0 {
		for _, e := range m.ContractAuthorizations {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryCodeAuthorizationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCodeAuthorizationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCodeAuthorizationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeId", wireType)
			}
			m.CodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CodeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCodeAuthorizationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCodeAuthorizationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCodeAuthorizationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Methods", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Methods = append(m.Methods, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryContractAuthorizationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryContractAuthorizationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryContractAuthorizationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryContractAuthorizationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryContractAuthorizationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryContractAuthorizationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Methods", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Methods = append(m.Methods, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuthorizationsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuthorizationsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuthorizationsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuthorizationsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuthorizationsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuthorizationsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeAuthorizations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodeAuthorizations = append(m.CodeAuthorizations, &CodeAuthorization{})
			if err := m.CodeAuthorizations[len(m.CodeAuthorizations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAuthorizations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAuthorizations = append(m.ContractAuthorizations, &ContractAuthorization{})
			if err := m.ContractAuthorizations[len(m.ContractAuthorizations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
