// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stakebird/curating/v1beta1/curating.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/golang/protobuf/ptypes/duration"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	VendorID        uint32                                        `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id" yaml:"vendor_id"`
	PostIDHash      []byte                                        `protobuf:"bytes,2,opt,name=post_id_hash,json=postIdHash,proto3" json:"post_id_hash" yaml:"post_id_hash"`
	Creator         github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,3,opt,name=creator,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"creator,omitempty" yaml:"creator"`
	RewardAccount   github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,4,opt,name=reward_account,json=rewardAccount,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"reward_account,omitempty" yaml:"reward_account"`
	BodyHash        []byte                                        `protobuf:"bytes,5,opt,name=body_hash,json=bodyHash,proto3" json:"body_hash,omitempty" yaml:"body_hash"`
	CuratingEndTime time.Time                                     `protobuf:"bytes,7,opt,name=curating_end_time,json=curatingEndTime,proto3,stdtime" json:"curating_end_time" yaml:"curating_end_time"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9830762980cde9, []int{0}
}
func (m *Post) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Post.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return m.Size()
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetVendorID() uint32 {
	if m != nil {
		return m.VendorID
	}
	return 0
}

func (m *Post) GetPostIDHash() []byte {
	if m != nil {
		return m.PostIDHash
	}
	return nil
}

func (m *Post) GetCreator() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *Post) GetRewardAccount() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.RewardAccount
	}
	return nil
}

func (m *Post) GetBodyHash() []byte {
	if m != nil {
		return m.BodyHash
	}
	return nil
}

func (m *Post) GetCuratingEndTime() time.Time {
	if m != nil {
		return m.CuratingEndTime
	}
	return time.Time{}
}

type Upvote struct {
	Curator       github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=curator,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"curator,omitempty" yaml:"curator"`
	RewardAccount github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,2,opt,name=reward_account,json=rewardAccount,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"reward_account,omitempty" yaml:"reward_account"`
	VoteAmount    types.Coin                                    `protobuf:"bytes,3,opt,name=vote_amount,json=voteAmount,proto3" json:"vote_amount"`
	CuratedTime   time.Time                                     `protobuf:"bytes,5,opt,name=curated_time,json=curatedTime,proto3,stdtime" json:"curated_time" yaml:"curated_time"`
}

func (m *Upvote) Reset()         { *m = Upvote{} }
func (m *Upvote) String() string { return proto.CompactTextString(m) }
func (*Upvote) ProtoMessage()    {}
func (*Upvote) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9830762980cde9, []int{1}
}
func (m *Upvote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Upvote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Upvote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Upvote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Upvote.Merge(m, src)
}
func (m *Upvote) XXX_Size() int {
	return m.Size()
}
func (m *Upvote) XXX_DiscardUnknown() {
	xxx_messageInfo_Upvote.DiscardUnknown(m)
}

var xxx_messageInfo_Upvote proto.InternalMessageInfo

func (m *Upvote) GetCurator() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Curator
	}
	return nil
}

func (m *Upvote) GetRewardAccount() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.RewardAccount
	}
	return nil
}

func (m *Upvote) GetVoteAmount() types.Coin {
	if m != nil {
		return m.VoteAmount
	}
	return types.Coin{}
}

func (m *Upvote) GetCuratedTime() time.Time {
	if m != nil {
		return m.CuratedTime
	}
	return time.Time{}
}

// VPPair is struct that just has a vendor_id, post_id pair with no other data.
// It is intended to be used as a marshalable pointer. For example, a VPPair can
// be used to construct the key to getting an Upvote from state.
type VPPair struct {
	VendorID   uint32 `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id" yaml:"vendor_id"`
	PostIDHash []byte `protobuf:"bytes,2,opt,name=post_id_hash,json=postIdHash,proto3" json:"post_id_hash" yaml:"post_id_hash"`
}

func (m *VPPair) Reset()         { *m = VPPair{} }
func (m *VPPair) String() string { return proto.CompactTextString(m) }
func (*VPPair) ProtoMessage()    {}
func (*VPPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9830762980cde9, []int{2}
}
func (m *VPPair) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VPPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VPPair.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VPPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPPair.Merge(m, src)
}
func (m *VPPair) XXX_Size() int {
	return m.Size()
}
func (m *VPPair) XXX_DiscardUnknown() {
	xxx_messageInfo_VPPair.DiscardUnknown(m)
}

var xxx_messageInfo_VPPair proto.InternalMessageInfo

func (m *VPPair) GetVendorID() uint32 {
	if m != nil {
		return m.VendorID
	}
	return 0
}

func (m *VPPair) GetPostIDHash() []byte {
	if m != nil {
		return m.PostIDHash
	}
	return nil
}

// VPPairs defines an array of VPPair objects.
type VPPairs struct {
	Pairs []VPPair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs"`
}

func (m *VPPairs) Reset()         { *m = VPPairs{} }
func (m *VPPairs) String() string { return proto.CompactTextString(m) }
func (*VPPairs) ProtoMessage()    {}
func (*VPPairs) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9830762980cde9, []int{3}
}
func (m *VPPairs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VPPairs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VPPairs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VPPairs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPPairs.Merge(m, src)
}
func (m *VPPairs) XXX_Size() int {
	return m.Size()
}
func (m *VPPairs) XXX_DiscardUnknown() {
	xxx_messageInfo_VPPairs.DiscardUnknown(m)
}

var xxx_messageInfo_VPPairs proto.InternalMessageInfo

func (m *VPPairs) GetPairs() []VPPair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type Params struct {
	CreatorAllocation          github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=creator_allocation,json=creatorAllocation,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"creator_allocation,omitempty" yaml:"creator_allocation"`
	RewardPoolCurationMaxAlloc github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,7,opt,name=reward_pool_curation_max_alloc,json=rewardPoolCurationMaxAlloc,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"reward_pool_curation_max_alloc,omitempty" yaml:"reward_pool_curation_max_alloc"`
	CurationWindow             time.Duration                          `protobuf:"bytes,1,opt,name=curation_window,json=curationWindow,proto3,stdduration" json:"curation_window" yaml:"curation_window"`
	VoteAmount                 types.Coin                             `protobuf:"bytes,2,opt,name=vote_amount,json=voteAmount,proto3" json:"vote_amount" yaml:"vote_amount"`
	MaxNumVotes                uint32                                 `protobuf:"varint,3,opt,name=max_num_votes,json=maxNumVotes,proto3" json:"max_num_votes" yaml:"max_num_votes"`
	MaxVendors                 uint32                                 `protobuf:"varint,4,opt,name=max_vendors,json=maxVendors,proto3" json:"max_vendors" yaml:"max_vendors"`
	RewardPoolAllocation       github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,5,opt,name=reward_pool_allocation,json=rewardPoolAllocation,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"reward_pool_allocation" yaml:"reward_pool_allocation"`
	InitialRewardPool          types.Coin                             `protobuf:"bytes,8,opt,name=initial_reward_pool,json=initialRewardPool,proto3" json:"initial_reward_pool" yaml:"initial_reward_pool"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9830762980cde9, []int{4}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetCurationWindow() time.Duration {
	if m != nil {
		return m.CurationWindow
	}
	return 0
}

func (m *Params) GetVoteAmount() types.Coin {
	if m != nil {
		return m.VoteAmount
	}
	return types.Coin{}
}

func (m *Params) GetMaxNumVotes() uint32 {
	if m != nil {
		return m.MaxNumVotes
	}
	return 0
}

func (m *Params) GetMaxVendors() uint32 {
	if m != nil {
		return m.MaxVendors
	}
	return 0
}

func (m *Params) GetInitialRewardPool() types.Coin {
	if m != nil {
		return m.InitialRewardPool
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Post)(nil), "stakebird.user.v1beta1.Post")
	proto.RegisterType((*Upvote)(nil), "stakebird.user.v1beta1.Upvote")
	proto.RegisterType((*VPPair)(nil), "stakebird.user.v1beta1.VPPair")
	proto.RegisterType((*VPPairs)(nil), "stakebird.user.v1beta1.VPPairs")
	proto.RegisterType((*Params)(nil), "stakebird.user.v1beta1.Params")
}

func init() {
	proto.RegisterFile("stakebird/curating/v1beta1/curating.proto", fileDescriptor_9b9830762980cde9)
}

var fileDescriptor_9b9830762980cde9 = []byte{
	// 972 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0xae, 0xdb, 0x34, 0x4d, 0x27, 0x4d, 0x97, 0xba, 0xa5, 0xca, 0x46, 0x90, 0x89, 0x2c, 0x16,
	0xa5, 0x12, 0x75, 0xd4, 0x05, 0x0e, 0xf4, 0x44, 0xdc, 0x2e, 0xa2, 0x2b, 0xed, 0x12, 0x59, 0xd0,
	0x95, 0x90, 0xc0, 0x9a, 0xd8, 0xb3, 0xa9, 0xd5, 0xd8, 0x63, 0x3c, 0x4e, 0x9b, 0x9e, 0x81, 0xfb,
	0x1e, 0x2b, 0x0e, 0xa8, 0xff, 0x82, 0xbf, 0xd0, 0xe3, 0x1e, 0x11, 0x87, 0x01, 0xa5, 0x17, 0x14,
	0x6e, 0x3e, 0x22, 0x0e, 0x68, 0x3e, 0x92, 0xd8, 0xdd, 0x42, 0xd9, 0x95, 0x38, 0xec, 0x29, 0x9e,
	0xe7, 0xfd, 0xf4, 0xf3, 0x3e, 0xef, 0xc4, 0x60, 0x8b, 0x26, 0xe8, 0x18, 0x77, 0xfd, 0xd8, 0x6b,
	0xb9, 0x83, 0x18, 0x25, 0x7e, 0xd8, 0x6b, 0x9d, 0xec, 0x74, 0x71, 0x82, 0x76, 0xa6, 0x80, 0x19,
	0xc5, 0x24, 0x21, 0xfa, 0xe6, 0xd4, 0xd5, 0x1c, 0x50, 0x1c, 0x9b, 0xca, 0xad, 0xb6, 0xd1, 0x23,
	0x3d, 0x22, 0x5c, 0x5a, 0xfc, 0x49, 0x7a, 0xd7, 0xea, 0x2e, 0xa1, 0x01, 0xa1, 0xad, 0x2e, 0xa2,
	0x78, 0x96, 0x91, 0xf8, 0xa1, 0xb2, 0xc3, 0x1e, 0x21, 0xbd, 0x3e, 0x6e, 0x89, 0x53, 0x77, 0xf0,
	0xb4, 0x95, 0xf8, 0x01, 0xa6, 0x09, 0x0a, 0xa2, 0x49, 0x82, 0xeb, 0x0e, 0x9e, 0x68, 0x87, 0xa8,
	0x04, 0xc6, 0x8f, 0x05, 0x50, 0xe8, 0x10, 0x9a, 0xe8, 0x0f, 0xc1, 0xf2, 0x09, 0x0e, 0x3d, 0x12,
	0x3b, 0xbe, 0x57, 0xd5, 0x1a, 0x5a, 0xb3, 0x62, 0x6d, 0x8f, 0x18, 0x2c, 0x1d, 0x0a, 0xf0, 0x60,
	0x7f, 0xcc, 0xe0, 0xcc, 0x21, 0x65, 0xf0, 0x8d, 0x33, 0x14, 0xf4, 0x77, 0x8d, 0x29, 0x64, 0xd8,
	0x25, 0xf9, 0x7c, 0xe0, 0xe9, 0x4f, 0xc0, 0x4a, 0x44, 0x68, 0xe2, 0xf8, 0x9e, 0x73, 0x84, 0xe8,
	0x51, 0x75, 0xbe, 0xa1, 0x35, 0x57, 0xac, 0x0f, 0x47, 0x0c, 0x02, 0x5e, 0xeb, 0x60, 0xff, 0x53,
	0x44, 0x8f, 0xc6, 0x0c, 0xe6, 0xbc, 0x52, 0x06, 0xd7, 0x65, 0xce, 0x2c, 0x6a, 0xd8, 0x80, 0x1f,
	0x0f, 0x3c, 0x1e, 0xa2, 0x7f, 0x05, 0x96, 0xdc, 0x18, 0xa3, 0x84, 0xc4, 0xd5, 0x05, 0x91, 0x73,
	0x2f, 0x65, 0x70, 0x55, 0x46, 0x29, 0x83, 0xf1, 0x27, 0x83, 0xdb, 0x3d, 0x3f, 0x39, 0x1a, 0x74,
	0x4d, 0x97, 0x04, 0x2d, 0x45, 0xa0, 0xfc, 0xd9, 0xa6, 0xde, 0x71, 0x2b, 0x39, 0x8b, 0x30, 0x35,
	0xdb, 0xae, 0xdb, 0xf6, 0xbc, 0x18, 0x53, 0x6a, 0x4f, 0x72, 0xea, 0xdf, 0x80, 0xd5, 0x18, 0x9f,
	0xa2, 0xd8, 0x73, 0x90, 0xeb, 0x92, 0x41, 0x98, 0x54, 0x0b, 0xa2, 0xca, 0xc3, 0x94, 0xc1, 0x37,
	0x65, 0x95, 0xbc, 0xfd, 0x15, 0x8a, 0x55, 0x64, 0x86, 0xb6, 0x4c, 0xa0, 0xef, 0x80, 0xe5, 0x2e,
	0xf1, 0xce, 0x24, 0x4f, 0x8b, 0xa2, 0xda, 0xc6, 0x8c, 0xdd, 0xa9, 0xc9, 0xb0, 0x4b, 0xfc, 0x59,
	0x90, 0xd0, 0x07, 0x6b, 0x13, 0x4d, 0x39, 0x38, 0xf4, 0x1c, 0x3e, 0xf2, 0xea, 0x52, 0x43, 0x6b,
	0x96, 0xef, 0xd7, 0x4c, 0x39, 0x6e, 0x73, 0x32, 0x6e, 0xf3, 0xf3, 0x89, 0x1e, 0xac, 0x77, 0x2e,
	0x19, 0x9c, 0x4b, 0x19, 0xac, 0x2a, 0xba, 0xae, 0xa7, 0x30, 0x9e, 0xfd, 0x0a, 0x35, 0xfb, 0xce,
	0x04, 0x7f, 0x10, 0x7a, 0x3c, 0xd6, 0xf8, 0x6b, 0x1e, 0x14, 0xbf, 0x88, 0x4e, 0x48, 0x82, 0x05,
	0xfb, 0xdc, 0x4a, 0x62, 0x21, 0x90, 0x3c, 0xfb, 0xd2, 0xf0, 0x4a, 0xec, 0xcb, 0xd0, 0x1b, 0xd8,
	0x9f, 0xff, 0xbf, 0xd9, 0xff, 0x18, 0x94, 0xf9, 0x9b, 0x39, 0x28, 0x10, 0xf5, 0x16, 0x04, 0x89,
	0x77, 0x4d, 0x99, 0xc1, 0xe4, 0x4b, 0x37, 0xd9, 0x4f, 0x73, 0x8f, 0xf8, 0xa1, 0x55, 0xe0, 0x1c,
	0xda, 0x80, 0xc7, 0xb4, 0x45, 0x88, 0xfe, 0x35, 0x58, 0x11, 0xfd, 0x63, 0x35, 0x87, 0xc5, 0x5b,
	0xe7, 0x00, 0xd5, 0x1c, 0xd6, 0x33, 0xc4, 0xe1, 0xec, 0x08, 0xca, 0x0a, 0x12, 0xf4, 0xff, 0xa4,
	0x81, 0xe2, 0x61, 0xa7, 0x83, 0xfc, 0xf8, 0xb5, 0xd8, 0xd0, 0xdd, 0xd2, 0xf9, 0x05, 0xd4, 0x7e,
	0xbf, 0x80, 0x9a, 0xf1, 0x00, 0x2c, 0xc9, 0xc6, 0xa9, 0xbe, 0x0b, 0x16, 0x23, 0xfe, 0x50, 0xd5,
	0x1a, 0x0b, 0xcd, 0xf2, 0xfd, 0xba, 0x79, 0xf3, 0x1d, 0x68, 0x4a, 0x7f, 0xc5, 0xb2, 0x0c, 0x31,
	0xfe, 0x58, 0x02, 0xc5, 0x0e, 0x8a, 0x51, 0x40, 0xf5, 0x1f, 0x34, 0xa0, 0xab, 0x55, 0x75, 0x50,
	0xbf, 0x4f, 0x5c, 0x71, 0x91, 0x55, 0x8b, 0x0d, 0xad, 0xb9, 0x6c, 0x1d, 0xf3, 0xa0, 0x5f, 0x18,
	0x7c, 0xf7, 0x3f, 0x08, 0x62, 0x1f, 0xbb, 0x63, 0x06, 0xdf, 0x7a, 0x31, 0xd7, 0x7b, 0x24, 0xf0,
	0x13, 0x1c, 0x44, 0xc9, 0x59, 0xca, 0xe0, 0xdd, 0xdc, 0xbd, 0x92, 0xf1, 0x32, 0xec, 0x35, 0x05,
	0xb6, 0xa7, 0x98, 0x7e, 0xa9, 0x81, 0xba, 0x92, 0x67, 0x44, 0x48, 0xdf, 0x71, 0xd5, 0x3d, 0xeb,
	0x04, 0x68, 0x28, 0x63, 0xc5, 0x8e, 0x2e, 0x5b, 0xdf, 0x6a, 0x2f, 0xdd, 0x69, 0xf3, 0xdf, 0x13,
	0xe7, 0xba, 0xbe, 0x97, 0xdb, 0x94, 0x7f, 0x88, 0x30, 0xec, 0x9a, 0x74, 0xe8, 0x10, 0xd2, 0xdf,
	0x53, 0xe6, 0x47, 0x68, 0x28, 0xde, 0x47, 0x7f, 0x0a, 0xee, 0x4c, 0x43, 0x4e, 0xfd, 0xd0, 0x23,
	0xa7, 0x42, 0x6e, 0x7c, 0x33, 0xae, 0xcb, 0x7a, 0x5f, 0xf9, 0x59, 0x86, 0x52, 0xf5, 0x66, 0xf6,
	0x76, 0x99, 0xc6, 0x1b, 0xe7, 0x5c, 0xd8, 0xab, 0x13, 0xf4, 0x89, 0x00, 0x75, 0x9c, 0xdf, 0xbe,
	0xf9, 0xdb, 0xb6, 0x6f, 0x8b, 0xd7, 0x18, 0x33, 0x98, 0x8d, 0x4a, 0x19, 0xd4, 0x95, 0xce, 0x67,
	0xa0, 0x91, 0x5b, 0xd1, 0x47, 0xa0, 0xc2, 0x5f, 0x3c, 0x1c, 0x04, 0x0e, 0x47, 0xa9, 0x58, 0xf3,
	0x8a, 0xb5, 0x35, 0x66, 0x30, 0x6f, 0x48, 0x19, 0xdc, 0x90, 0xb9, 0x72, 0xb0, 0x61, 0x97, 0x03,
	0x34, 0x7c, 0x3c, 0x08, 0x0e, 0xf9, 0x49, 0xff, 0x04, 0xf0, 0xa3, 0x23, 0x57, 0x89, 0x8a, 0x7f,
	0x88, 0x8a, 0x75, 0x8f, 0xb7, 0x95, 0x81, 0x67, 0x6d, 0x65, 0x40, 0xc3, 0x06, 0x01, 0x1a, 0xca,
	0x75, 0xa5, 0xfa, 0xf7, 0x1a, 0xd8, 0xcc, 0x4e, 0x29, 0xa3, 0x68, 0xf9, 0x3f, 0xf0, 0xd9, 0xcb,
	0xe9, 0x24, 0x65, 0xf0, 0xed, 0x17, 0x67, 0x9f, 0x55, 0xed, 0xc6, 0x6c, 0xe6, 0x19, 0xe1, 0x7e,
	0xa7, 0x81, 0x75, 0x3f, 0xf4, 0x13, 0x1f, 0xf5, 0x9d, 0x4c, 0x64, 0xb5, 0x74, 0xdb, 0x38, 0x3e,
	0x52, 0xe3, 0xb8, 0x29, 0x3a, 0x65, 0xb0, 0x26, 0x9b, 0xb9, 0xc1, 0x68, 0xd8, 0x6b, 0x0a, 0xb5,
	0xa7, 0x0d, 0xed, 0x16, 0xce, 0x2f, 0xe0, 0x9c, 0xf5, 0xf8, 0x72, 0x54, 0xd7, 0x9e, 0x8f, 0xea,
	0xda, 0x6f, 0xa3, 0xba, 0xf6, 0xec, 0xaa, 0x3e, 0xf7, 0xfc, 0xaa, 0x3e, 0xf7, 0xf3, 0x55, 0x7d,
	0xee, 0xcb, 0x0f, 0x32, 0x2c, 0x44, 0x83, 0x6e, 0xdf, 0x77, 0xb7, 0xd1, 0x29, 0xa6, 0x24, 0xc0,
	0xad, 0xd9, 0xc7, 0xd7, 0x70, 0xf6, 0xf9, 0x25, 0x78, 0xe9, 0x16, 0x85, 0x52, 0xdf, 0xff, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0xb6, 0xf4, 0x12, 0x02, 0xa1, 0x09, 0x00, 0x00,
}

func (this *VPPair) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VPPair)
	if !ok {
		that2, ok := that.(VPPair)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.VendorID != that1.VendorID {
		return false
	}
	if !bytes.Equal(this.PostIDHash, that1.PostIDHash) {
		return false
	}
	return true
}
func (m *Post) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Post) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Post) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CuratingEndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CuratingEndTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintCurating(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x3a
	if len(m.BodyHash) > 0 {
		i -= len(m.BodyHash)
		copy(dAtA[i:], m.BodyHash)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.BodyHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RewardAccount) > 0 {
		i -= len(m.RewardAccount)
		copy(dAtA[i:], m.RewardAccount)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.RewardAccount)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PostIDHash) > 0 {
		i -= len(m.PostIDHash)
		copy(dAtA[i:], m.PostIDHash)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.PostIDHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.VendorID != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.VendorID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Upvote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Upvote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Upvote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CuratedTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CuratedTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintCurating(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.VoteAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.RewardAccount) > 0 {
		i -= len(m.RewardAccount)
		copy(dAtA[i:], m.RewardAccount)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.RewardAccount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Curator) > 0 {
		i -= len(m.Curator)
		copy(dAtA[i:], m.Curator)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.Curator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VPPair) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VPPair) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VPPair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PostIDHash) > 0 {
		i -= len(m.PostIDHash)
		copy(dAtA[i:], m.PostIDHash)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.PostIDHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.VendorID != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.VendorID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *VPPairs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VPPairs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VPPairs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Pairs) > 0 {
		for iNdEx := len(m.Pairs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pairs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCurating(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.InitialRewardPool.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.RewardPoolCurationMaxAlloc.Size()
		i -= size
		if _, err := m.RewardPoolCurationMaxAlloc.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.CreatorAllocation.Size()
		i -= size
		if _, err := m.CreatorAllocation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.RewardPoolAllocation.Size()
		i -= size
		if _, err := m.RewardPoolAllocation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.MaxVendors != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.MaxVendors))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxNumVotes != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.MaxNumVotes))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.VoteAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	n6, err6 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.CurationWindow, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.CurationWindow):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintCurating(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintCurating(dAtA []byte, offset int, v uint64) int {
	offset -= sovCurating(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Post) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VendorID != 0 {
		n += 1 + sovCurating(uint64(m.VendorID))
	}
	l = len(m.PostIDHash)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = len(m.RewardAccount)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = len(m.BodyHash)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CuratingEndTime)
	n += 1 + l + sovCurating(uint64(l))
	return n
}

func (m *Upvote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Curator)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = len(m.RewardAccount)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = m.VoteAmount.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CuratedTime)
	n += 1 + l + sovCurating(uint64(l))
	return n
}

func (m *VPPair) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VendorID != 0 {
		n += 1 + sovCurating(uint64(m.VendorID))
	}
	l = len(m.PostIDHash)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	return n
}

func (m *VPPairs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Pairs) > 0 {
		for _, e := range m.Pairs {
			l = e.Size()
			n += 1 + l + sovCurating(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.CurationWindow)
	n += 1 + l + sovCurating(uint64(l))
	l = m.VoteAmount.Size()
	n += 1 + l + sovCurating(uint64(l))
	if m.MaxNumVotes != 0 {
		n += 1 + sovCurating(uint64(m.MaxNumVotes))
	}
	if m.MaxVendors != 0 {
		n += 1 + sovCurating(uint64(m.MaxVendors))
	}
	l = m.RewardPoolAllocation.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = m.CreatorAllocation.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = m.RewardPoolCurationMaxAlloc.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = m.InitialRewardPool.Size()
	n += 1 + l + sovCurating(uint64(l))
	return n
}

func sovCurating(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCurating(x uint64) (n int) {
	return sovCurating(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Post) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Post: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Post: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorID", wireType)
			}
			m.VendorID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VendorID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostIDHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PostIDHash = append(m.PostIDHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PostIDHash == nil {
				m.PostIDHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = append(m.Creator[:0], dAtA[iNdEx:postIndex]...)
			if m.Creator == nil {
				m.Creator = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAccount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAccount = append(m.RewardAccount[:0], dAtA[iNdEx:postIndex]...)
			if m.RewardAccount == nil {
				m.RewardAccount = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BodyHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BodyHash = append(m.BodyHash[:0], dAtA[iNdEx:postIndex]...)
			if m.BodyHash == nil {
				m.BodyHash = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CuratingEndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CuratingEndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCurating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Upvote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Upvote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Upvote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Curator", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Curator = append(m.Curator[:0], dAtA[iNdEx:postIndex]...)
			if m.Curator == nil {
				m.Curator = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAccount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAccount = append(m.RewardAccount[:0], dAtA[iNdEx:postIndex]...)
			if m.RewardAccount == nil {
				m.RewardAccount = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VoteAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CuratedTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CuratedTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCurating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VPPair) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VPPair: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VPPair: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorID", wireType)
			}
			m.VendorID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VendorID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostIDHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PostIDHash = append(m.PostIDHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PostIDHash == nil {
				m.PostIDHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCurating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VPPairs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VPPairs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VPPairs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pairs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pairs = append(m.Pairs, VPPair{})
			if err := m.Pairs[len(m.Pairs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCurating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurationWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.CurationWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VoteAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxNumVotes", wireType)
			}
			m.MaxNumVotes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxNumVotes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxVendors", wireType)
			}
			m.MaxVendors = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxVendors |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardPoolAllocation", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RewardPoolAllocation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorAllocation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CreatorAllocation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardPoolCurationMaxAlloc", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RewardPoolCurationMaxAlloc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialRewardPool", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialRewardPool.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCurating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCurating(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCurating
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCurating
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCurating
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCurating        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCurating          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCurating = fmt.Errorf("proto: unexpected end of group")
)
