// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stakebird/curating/v1beta1/curating.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/golang/protobuf/ptypes/duration"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	VendorID        uint32    `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id" yaml:"vendor_id"`
	PostID          []byte    `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id" yaml:"post_id"`
	Creator         string    `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty" yaml:"creator"`
	RewardAccount   string    `protobuf:"bytes,4,opt,name=reward_account,json=rewardAccount,proto3" json:"reward_account,omitempty" yaml:"reward_account"`
	BodyHash        []byte    `protobuf:"bytes,5,opt,name=body_hash,json=bodyHash,proto3" json:"body_hash,omitempty" yaml:"body_hash"`
	CuratingEndTime time.Time `protobuf:"bytes,7,opt,name=curating_end_time,json=curatingEndTime,proto3,stdtime" json:"curating_end_time" yaml:"curating_end_time"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9830762980cde9, []int{0}
}
func (m *Post) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Post.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return m.Size()
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetVendorID() uint32 {
	if m != nil {
		return m.VendorID
	}
	return 0
}

func (m *Post) GetPostID() []byte {
	if m != nil {
		return m.PostID
	}
	return nil
}

func (m *Post) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Post) GetRewardAccount() string {
	if m != nil {
		return m.RewardAccount
	}
	return ""
}

func (m *Post) GetBodyHash() []byte {
	if m != nil {
		return m.BodyHash
	}
	return nil
}

func (m *Post) GetCuratingEndTime() time.Time {
	if m != nil {
		return m.CuratingEndTime
	}
	return time.Time{}
}

type Upvote struct {
	VendorID      uint32     `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id" yaml:"vendor_id"`
	PostID        []byte     `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id" yaml:"post_id"`
	Curator       string     `protobuf:"bytes,3,opt,name=curator,proto3" json:"curator,omitempty" yaml:"curator"`
	RewardAccount string     `protobuf:"bytes,4,opt,name=reward_account,json=rewardAccount,proto3" json:"reward_account,omitempty" yaml:"reward_account"`
	VoteAmount    types.Coin `protobuf:"bytes,5,opt,name=vote_amount,json=voteAmount,proto3" json:"vote_amount"`
	CuratedTime   time.Time  `protobuf:"bytes,6,opt,name=curated_time,json=curatedTime,proto3,stdtime" json:"curated_time" yaml:"curated_time"`
}

func (m *Upvote) Reset()         { *m = Upvote{} }
func (m *Upvote) String() string { return proto.CompactTextString(m) }
func (*Upvote) ProtoMessage()    {}
func (*Upvote) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9830762980cde9, []int{1}
}
func (m *Upvote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Upvote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Upvote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Upvote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Upvote.Merge(m, src)
}
func (m *Upvote) XXX_Size() int {
	return m.Size()
}
func (m *Upvote) XXX_DiscardUnknown() {
	xxx_messageInfo_Upvote.DiscardUnknown(m)
}

var xxx_messageInfo_Upvote proto.InternalMessageInfo

func (m *Upvote) GetVendorID() uint32 {
	if m != nil {
		return m.VendorID
	}
	return 0
}

func (m *Upvote) GetPostID() []byte {
	if m != nil {
		return m.PostID
	}
	return nil
}

func (m *Upvote) GetCurator() string {
	if m != nil {
		return m.Curator
	}
	return ""
}

func (m *Upvote) GetRewardAccount() string {
	if m != nil {
		return m.RewardAccount
	}
	return ""
}

func (m *Upvote) GetVoteAmount() types.Coin {
	if m != nil {
		return m.VoteAmount
	}
	return types.Coin{}
}

func (m *Upvote) GetCuratedTime() time.Time {
	if m != nil {
		return m.CuratedTime
	}
	return time.Time{}
}

// VPPair is struct that just has a vendor_id, post_id pair with no other data.
// It is intended to be used as a marshalable pointer. For example, a VPPair can
// be used to construct the key to getting an Upvote from state.
type VPPair struct {
	VendorID uint32 `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id" yaml:"vendor_id"`
	PostID   []byte `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id" yaml:"post_id"`
}

func (m *VPPair) Reset()         { *m = VPPair{} }
func (m *VPPair) String() string { return proto.CompactTextString(m) }
func (*VPPair) ProtoMessage()    {}
func (*VPPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9830762980cde9, []int{2}
}
func (m *VPPair) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VPPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VPPair.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VPPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPPair.Merge(m, src)
}
func (m *VPPair) XXX_Size() int {
	return m.Size()
}
func (m *VPPair) XXX_DiscardUnknown() {
	xxx_messageInfo_VPPair.DiscardUnknown(m)
}

var xxx_messageInfo_VPPair proto.InternalMessageInfo

func (m *VPPair) GetVendorID() uint32 {
	if m != nil {
		return m.VendorID
	}
	return 0
}

func (m *VPPair) GetPostID() []byte {
	if m != nil {
		return m.PostID
	}
	return nil
}

// VPPairs defines an array of VPPair objects.
type VPPairs struct {
	Pairs []VPPair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs"`
}

func (m *VPPairs) Reset()         { *m = VPPairs{} }
func (m *VPPairs) String() string { return proto.CompactTextString(m) }
func (*VPPairs) ProtoMessage()    {}
func (*VPPairs) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9830762980cde9, []int{3}
}
func (m *VPPairs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VPPairs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VPPairs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VPPairs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPPairs.Merge(m, src)
}
func (m *VPPairs) XXX_Size() int {
	return m.Size()
}
func (m *VPPairs) XXX_DiscardUnknown() {
	xxx_messageInfo_VPPairs.DiscardUnknown(m)
}

var xxx_messageInfo_VPPairs proto.InternalMessageInfo

func (m *VPPairs) GetPairs() []VPPair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type Params struct {
	CurationWindow                  time.Duration                          `protobuf:"bytes,1,opt,name=curation_window,json=curationWindow,proto3,stdduration" json:"curation_window" yaml:"curation_window"`
	VoteAmount                      types.Coin                             `protobuf:"bytes,2,opt,name=vote_amount,json=voteAmount,proto3" json:"vote_amount" yaml:"vote_amount"`
	MaxNumVotes                     uint32                                 `protobuf:"varint,3,opt,name=max_num_votes,json=maxNumVotes,proto3" json:"max_num_votes" yaml:"max_num_votes"`
	MaxVendors                      uint32                                 `protobuf:"varint,4,opt,name=max_vendors,json=maxVendors,proto3" json:"max_vendors" yaml:"max_vendors"`
	RewardPoolAllocation            github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,5,opt,name=reward_pool_allocation,json=rewardPoolAllocation,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"reward_pool_allocation" yaml:"reward_pool_allocation"`
	CreatorProtocolRewardAllocation github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=creator_protocol_reward_allocation,json=creatorProtocolRewardAllocation,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"creator_protocol_reward_allocation,omitempty" yaml:"creator_protocol_reward_allocation"`
	CreatorVotingRewardAllocation   github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,7,opt,name=creator_voting_reward_allocation,json=creatorVotingRewardAllocation,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"creator_voting_reward_allocation,omitempty" yaml:"creator_voting_reward_allocation"`
	RewardPoolCurationMaxAlloc      github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,8,opt,name=reward_pool_curation_max_alloc,json=rewardPoolCurationMaxAlloc,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"reward_pool_curation_max_alloc,omitempty" yaml:"reward_pool_curation_max_alloc"`
	InitialRewardPool               types.Coin                             `protobuf:"bytes,9,opt,name=initial_reward_pool,json=initialRewardPool,proto3" json:"initial_reward_pool" yaml:"initial_reward_pool"`
	StakeDenom                      string                                 `protobuf:"bytes,10,opt,name=stake_denom,json=stakeDenom,proto3" json:"stake_denom" yaml:"stake_denom"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9830762980cde9, []int{4}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetCurationWindow() time.Duration {
	if m != nil {
		return m.CurationWindow
	}
	return 0
}

func (m *Params) GetVoteAmount() types.Coin {
	if m != nil {
		return m.VoteAmount
	}
	return types.Coin{}
}

func (m *Params) GetMaxNumVotes() uint32 {
	if m != nil {
		return m.MaxNumVotes
	}
	return 0
}

func (m *Params) GetMaxVendors() uint32 {
	if m != nil {
		return m.MaxVendors
	}
	return 0
}

func (m *Params) GetInitialRewardPool() types.Coin {
	if m != nil {
		return m.InitialRewardPool
	}
	return types.Coin{}
}

func (m *Params) GetStakeDenom() string {
	if m != nil {
		return m.StakeDenom
	}
	return ""
}

func init() {
	proto.RegisterType((*Post)(nil), "stakebird.curating.v1beta1.Post")
	proto.RegisterType((*Upvote)(nil), "stakebird.curating.v1beta1.Upvote")
	proto.RegisterType((*VPPair)(nil), "stakebird.curating.v1beta1.VPPair")
	proto.RegisterType((*VPPairs)(nil), "stakebird.curating.v1beta1.VPPairs")
	proto.RegisterType((*Params)(nil), "stakebird.curating.v1beta1.Params")
}

func init() {
	proto.RegisterFile("stakebird/curating/v1beta1/curating.proto", fileDescriptor_9b9830762980cde9)
}

var fileDescriptor_9b9830762980cde9 = []byte{
	// 1015 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcd, 0x6f, 0x1b, 0x45,
	0x14, 0xf7, 0x36, 0x89, 0x3f, 0xc6, 0x75, 0xa0, 0xdb, 0x50, 0x6d, 0x2d, 0xd5, 0x63, 0x8d, 0x28,
	0x75, 0x50, 0xb2, 0x56, 0x0a, 0x17, 0x72, 0x40, 0xc9, 0x36, 0x20, 0x82, 0xd4, 0x62, 0xad, 0x20,
	0x48, 0x1c, 0x58, 0x8d, 0x77, 0xa7, 0xce, 0xaa, 0xde, 0x1d, 0x6b, 0x77, 0x9d, 0x38, 0x67, 0x40,
	0x1c, 0xb8, 0xf4, 0x98, 0x63, 0x2e, 0x48, 0xfc, 0x25, 0x28, 0xc7, 0x72, 0x03, 0x0e, 0x0b, 0x72,
	0x2e, 0x28, 0x47, 0xff, 0x05, 0x68, 0x3e, 0xf6, 0x2b, 0x49, 0x6b, 0x45, 0xea, 0x21, 0xa7, 0xcc,
	0xfc, 0xde, 0xc7, 0xbe, 0xdf, 0xfb, 0xbd, 0x37, 0x31, 0x58, 0x0d, 0x23, 0xfc, 0x82, 0xf4, 0xdd,
	0xc0, 0xe9, 0xda, 0xe3, 0x00, 0x47, 0xae, 0x3f, 0xe8, 0x1e, 0x6c, 0xf4, 0x49, 0x84, 0x37, 0x52,
	0x40, 0x1f, 0x05, 0x34, 0xa2, 0x6a, 0x33, 0x75, 0xd5, 0x53, 0x8b, 0x74, 0x6d, 0xae, 0x0c, 0xe8,
	0x80, 0x72, 0xb7, 0x2e, 0x3b, 0x89, 0x88, 0x66, 0xcb, 0xa6, 0xa1, 0x47, 0xc3, 0x6e, 0x1f, 0x87,
	0x24, 0xcb, 0x4a, 0x5d, 0x5f, 0xda, 0xe1, 0x80, 0xd2, 0xc1, 0x90, 0x74, 0xf9, 0xad, 0x3f, 0x7e,
	0xde, 0x8d, 0x5c, 0x8f, 0x84, 0x11, 0xf6, 0x46, 0x49, 0x82, 0x8b, 0x0e, 0x0e, 0xff, 0x30, 0x95,
	0x09, 0xd0, 0xaf, 0x0b, 0x60, 0xb1, 0x47, 0xc3, 0x48, 0xfd, 0x12, 0xd4, 0x0e, 0x88, 0xef, 0xd0,
	0xc0, 0x72, 0x1d, 0x4d, 0x69, 0x2b, 0x9d, 0x86, 0xb1, 0x3e, 0x8d, 0x61, 0x75, 0x8f, 0x83, 0xbb,
	0x3b, 0xe7, 0x31, 0xcc, 0x1c, 0x66, 0x31, 0x7c, 0xf7, 0x08, 0x7b, 0xc3, 0x4d, 0x94, 0x42, 0xc8,
	0xac, 0x8a, 0xf3, 0xae, 0xa3, 0x6e, 0x81, 0xca, 0x88, 0x86, 0x11, 0xcb, 0x74, 0xab, 0xad, 0x74,
	0x6e, 0x1b, 0x8f, 0xa6, 0x31, 0x2c, 0xb3, 0xcf, 0xf0, 0x3c, 0x89, 0x71, 0x16, 0xc3, 0x65, 0x91,
	0x45, 0x02, 0xc8, 0x2c, 0xb3, 0xd3, 0xae, 0xa3, 0xae, 0x81, 0x8a, 0x1d, 0x10, 0x1c, 0xd1, 0x40,
	0x5b, 0x68, 0x2b, 0x9d, 0x9a, 0xa1, 0x66, 0xce, 0xd2, 0x80, 0xcc, 0xc4, 0x45, 0xdd, 0x02, 0xcb,
	0x01, 0x39, 0xc4, 0x81, 0x63, 0x61, 0xdb, 0xa6, 0x63, 0x3f, 0xd2, 0x16, 0x79, 0xd0, 0xfd, 0x59,
	0x0c, 0xdf, 0x13, 0x41, 0x45, 0x3b, 0x32, 0x1b, 0x02, 0xd8, 0x16, 0x77, 0x75, 0x03, 0xd4, 0xfa,
	0xd4, 0x39, 0xb2, 0xf6, 0x71, 0xb8, 0xaf, 0x2d, 0xf1, 0x9a, 0x57, 0x32, 0x92, 0xa9, 0x09, 0x99,
	0x55, 0x76, 0xfe, 0x02, 0x87, 0xfb, 0xea, 0x10, 0xdc, 0x49, 0x44, 0xb4, 0x88, 0xef, 0x58, 0xac,
	0xf3, 0x5a, 0xa5, 0xad, 0x74, 0xea, 0x8f, 0x9b, 0xba, 0xe8, 0xba, 0x9e, 0x74, 0x5d, 0xff, 0x3a,
	0x91, 0xc5, 0x78, 0xff, 0x34, 0x86, 0xa5, 0x59, 0x0c, 0x35, 0x49, 0xe6, 0x62, 0x0a, 0xf4, 0xf2,
	0x1f, 0xa8, 0x98, 0xef, 0x24, 0xf8, 0x67, 0xbe, 0xc3, 0x62, 0xd1, 0x6f, 0x0b, 0xa0, 0xfc, 0xcd,
	0xe8, 0x80, 0x46, 0xe4, 0x06, 0x2a, 0xc5, 0x6a, 0xbd, 0x52, 0x29, 0x61, 0x60, 0x4a, 0x89, 0xd3,
	0x5b, 0x50, 0x6a, 0x0b, 0xd4, 0x59, 0x17, 0x2c, 0xec, 0xf1, 0xf0, 0x25, 0xde, 0xf0, 0xfb, 0xba,
	0xd8, 0x13, 0x9d, 0xed, 0x49, 0xb2, 0x52, 0xfa, 0x13, 0xea, 0xfa, 0xc6, 0x22, 0xeb, 0xb7, 0x09,
	0x58, 0xcc, 0x36, 0x0f, 0x51, 0xbf, 0x07, 0xb7, 0x79, 0x39, 0x44, 0x6a, 0x56, 0x9e, 0xab, 0x19,
	0x94, 0x9a, 0xdd, 0xcd, 0xd1, 0x22, 0x79, 0xb9, 0xea, 0x12, 0xe2, 0x52, 0x9d, 0x28, 0xa0, 0xbc,
	0xd7, 0xeb, 0x61, 0x37, 0xb8, 0x59, 0x52, 0x6d, 0x56, 0x8f, 0x4f, 0xa0, 0xf2, 0xdf, 0x09, 0x54,
	0xd0, 0x2e, 0xa8, 0x88, 0x0a, 0x43, 0xf5, 0x53, 0xb0, 0x34, 0x62, 0x07, 0x4d, 0x69, 0x2f, 0x74,
	0xea, 0x8f, 0x91, 0xfe, 0xfa, 0x37, 0x4a, 0x17, 0x31, 0xb2, 0xa5, 0x22, 0x0c, 0xfd, 0x0e, 0x40,
	0xb9, 0x87, 0x03, 0xec, 0x85, 0xea, 0x73, 0x20, 0xc7, 0x96, 0xfa, 0xd6, 0xa1, 0xeb, 0x3b, 0xf4,
	0x90, 0x73, 0x66, 0xf2, 0x5c, 0xec, 0xed, 0x8e, 0xf4, 0x33, 0x90, 0x6c, 0xed, 0xbd, 0xfc, 0x3a,
	0xa4, 0xf1, 0xe8, 0x98, 0x75, 0x77, 0x39, 0x41, 0xbf, 0xe5, 0xa0, 0x4a, 0x8a, 0x23, 0x70, 0x6b,
	0xde, 0x08, 0xac, 0xb2, 0x6f, 0x9c, 0xc7, 0x30, 0x1f, 0x35, 0x8b, 0xa1, 0x2a, 0x9b, 0x9d, 0x81,
	0xa8, 0x30, 0x27, 0x4f, 0x41, 0xc3, 0xc3, 0x13, 0xcb, 0x1f, 0x7b, 0x16, 0x43, 0x43, 0x3e, 0xdf,
	0x0d, 0x63, 0xf5, 0x3c, 0x86, 0x45, 0xc3, 0x2c, 0x86, 0x2b, 0x22, 0x57, 0x01, 0x46, 0x66, 0xdd,
	0xc3, 0x93, 0x67, 0x63, 0x6f, 0x8f, 0xdd, 0xd4, 0xcf, 0x01, 0xbb, 0x5a, 0x42, 0xcf, 0x90, 0xcf,
	0x7d, 0xc3, 0x78, 0xc8, 0xca, 0xca, 0xc1, 0x59, 0x59, 0x39, 0x10, 0x99, 0xc0, 0xc3, 0x13, 0x31,
	0x33, 0xa1, 0xfa, 0x93, 0x02, 0xee, 0xc9, 0x1d, 0x19, 0x51, 0x3a, 0xb4, 0xf0, 0x70, 0x48, 0x6d,
	0xde, 0x1e, 0xbe, 0x0c, 0x35, 0xe3, 0x2b, 0x46, 0xf7, 0xef, 0x18, 0x7e, 0x30, 0x70, 0xa3, 0xfd,
	0x71, 0x5f, 0xb7, 0xa9, 0xd7, 0x95, 0xff, 0x46, 0xc4, 0x9f, 0xf5, 0xd0, 0x79, 0xd1, 0x8d, 0x8e,
	0x46, 0x24, 0xd4, 0x77, 0x88, 0x3d, 0x8b, 0xe1, 0x83, 0xc2, 0xe6, 0x5d, 0xc8, 0x8a, 0xcc, 0x15,
	0x61, 0xe8, 0x51, 0x3a, 0xdc, 0x4e, 0x61, 0xf5, 0x2f, 0x05, 0x24, 0x4f, 0xb1, 0xc5, 0x75, 0xb5,
	0xe9, 0xd0, 0x4a, 0x96, 0x37, 0xab, 0xa9, 0xcc, 0x6b, 0xfa, 0x45, 0xb9, 0x5e, 0x51, 0xe7, 0x31,
	0x5c, 0x9b, 0x9f, 0x7c, 0x8d, 0x7a, 0x6e, 0x44, 0xbc, 0x51, 0x74, 0x34, 0x8b, 0xe1, 0x6a, 0xe1,
	0xbf, 0xc3, 0x1b, 0xa2, 0x90, 0x09, 0xa5, 0x53, 0x4f, 0xfa, 0x98, 0xe2, 0x85, 0xc9, 0xb8, 0xfd,
	0xa1, 0x80, 0x76, 0x92, 0xe8, 0x80, 0xf2, 0xf7, 0xf9, 0x32, 0xb3, 0x0a, 0x67, 0xf6, 0xf3, 0xf5,
	0x99, 0x7d, 0x38, 0x2f, 0x75, 0x81, 0xd7, 0xa3, 0x22, 0xaf, 0xd7, 0xc5, 0x20, 0xf3, 0x81, 0x74,
	0xd9, 0xe3, 0x1e, 0x97, 0x38, 0x9d, 0x2a, 0xa0, 0x95, 0x57, 0x38, 0x5d, 0x35, 0x36, 0x69, 0x3c,
	0x8f, 0x56, 0xe5, 0x8c, 0x7e, 0xb8, 0x3e, 0xa3, 0xce, 0x9b, 0x13, 0x17, 0xf8, 0x3c, 0xbc, 0x3c,
	0x6c, 0x97, 0x23, 0x90, 0xd9, 0xcc, 0x86, 0xee, 0x89, 0x34, 0x3f, 0xc5, 0x13, 0xce, 0x47, 0xfd,
	0x51, 0x01, 0x77, 0x5d, 0xdf, 0x8d, 0x5c, 0x9c, 0xca, 0xcb, 0xf2, 0x68, 0xb5, 0x79, 0x2f, 0xc1,
	0x27, 0xf2, 0x25, 0xb8, 0x2a, 0x7a, 0x16, 0xc3, 0xa6, 0x28, 0xed, 0x0a, 0x23, 0x32, 0xef, 0x48,
	0xd4, 0x4c, 0xcb, 0x62, 0x1b, 0xcd, 0x1f, 0x4b, 0xcb, 0x21, 0x3e, 0xf5, 0x34, 0xc0, 0xbb, 0xc7,
	0x37, 0x3a, 0x07, 0x67, 0x1b, 0x9d, 0x03, 0x91, 0x09, 0xf8, 0x6d, 0x87, 0x5d, 0x36, 0x17, 0x8f,
	0x4f, 0x60, 0xc9, 0x78, 0x76, 0x3a, 0x6d, 0x29, 0xaf, 0xa6, 0x2d, 0xe5, 0xdf, 0x69, 0x4b, 0x79,
	0x79, 0xd6, 0x2a, 0xbd, 0x3a, 0x6b, 0x95, 0xfe, 0x3c, 0x6b, 0x95, 0xbe, 0xfb, 0x38, 0xa7, 0xc3,
	0x68, 0xdc, 0x1f, 0xba, 0xf6, 0x3a, 0x3e, 0x24, 0x21, 0xf5, 0x48, 0x37, 0xfb, 0xed, 0x39, 0xc9,
	0x7e, 0x7d, 0x72, 0x65, 0xfa, 0x65, 0xbe, 0x01, 0x1f, 0xfd, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x66,
	0xaf, 0x02, 0xfd, 0xa0, 0x0a, 0x00, 0x00,
}

func (this *VPPair) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VPPair)
	if !ok {
		that2, ok := that.(VPPair)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.VendorID != that1.VendorID {
		return false
	}
	if !bytes.Equal(this.PostID, that1.PostID) {
		return false
	}
	return true
}
func (m *Post) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Post) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Post) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CuratingEndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CuratingEndTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintCurating(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x3a
	if len(m.BodyHash) > 0 {
		i -= len(m.BodyHash)
		copy(dAtA[i:], m.BodyHash)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.BodyHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RewardAccount) > 0 {
		i -= len(m.RewardAccount)
		copy(dAtA[i:], m.RewardAccount)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.RewardAccount)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PostID) > 0 {
		i -= len(m.PostID)
		copy(dAtA[i:], m.PostID)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.PostID)))
		i--
		dAtA[i] = 0x12
	}
	if m.VendorID != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.VendorID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Upvote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Upvote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Upvote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CuratedTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CuratedTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintCurating(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x32
	{
		size, err := m.VoteAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.RewardAccount) > 0 {
		i -= len(m.RewardAccount)
		copy(dAtA[i:], m.RewardAccount)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.RewardAccount)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Curator) > 0 {
		i -= len(m.Curator)
		copy(dAtA[i:], m.Curator)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.Curator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PostID) > 0 {
		i -= len(m.PostID)
		copy(dAtA[i:], m.PostID)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.PostID)))
		i--
		dAtA[i] = 0x12
	}
	if m.VendorID != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.VendorID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *VPPair) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VPPair) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VPPair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PostID) > 0 {
		i -= len(m.PostID)
		copy(dAtA[i:], m.PostID)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.PostID)))
		i--
		dAtA[i] = 0x12
	}
	if m.VendorID != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.VendorID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *VPPairs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VPPairs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VPPairs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Pairs) > 0 {
		for iNdEx := len(m.Pairs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pairs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCurating(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StakeDenom) > 0 {
		i -= len(m.StakeDenom)
		copy(dAtA[i:], m.StakeDenom)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.StakeDenom)))
		i--
		dAtA[i] = 0x52
	}
	{
		size, err := m.InitialRewardPool.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.RewardPoolCurationMaxAlloc.Size()
		i -= size
		if _, err := m.RewardPoolCurationMaxAlloc.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.CreatorVotingRewardAllocation.Size()
		i -= size
		if _, err := m.CreatorVotingRewardAllocation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.CreatorProtocolRewardAllocation.Size()
		i -= size
		if _, err := m.CreatorProtocolRewardAllocation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.RewardPoolAllocation.Size()
		i -= size
		if _, err := m.RewardPoolAllocation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.MaxVendors != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.MaxVendors))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxNumVotes != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.MaxNumVotes))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.VoteAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	n6, err6 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.CurationWindow, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.CurationWindow):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintCurating(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintCurating(dAtA []byte, offset int, v uint64) int {
	offset -= sovCurating(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Post) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VendorID != 0 {
		n += 1 + sovCurating(uint64(m.VendorID))
	}
	l = len(m.PostID)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = len(m.RewardAccount)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = len(m.BodyHash)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CuratingEndTime)
	n += 1 + l + sovCurating(uint64(l))
	return n
}

func (m *Upvote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VendorID != 0 {
		n += 1 + sovCurating(uint64(m.VendorID))
	}
	l = len(m.PostID)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = len(m.Curator)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = len(m.RewardAccount)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = m.VoteAmount.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CuratedTime)
	n += 1 + l + sovCurating(uint64(l))
	return n
}

func (m *VPPair) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VendorID != 0 {
		n += 1 + sovCurating(uint64(m.VendorID))
	}
	l = len(m.PostID)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	return n
}

func (m *VPPairs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Pairs) > 0 {
		for _, e := range m.Pairs {
			l = e.Size()
			n += 1 + l + sovCurating(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.CurationWindow)
	n += 1 + l + sovCurating(uint64(l))
	l = m.VoteAmount.Size()
	n += 1 + l + sovCurating(uint64(l))
	if m.MaxNumVotes != 0 {
		n += 1 + sovCurating(uint64(m.MaxNumVotes))
	}
	if m.MaxVendors != 0 {
		n += 1 + sovCurating(uint64(m.MaxVendors))
	}
	l = m.RewardPoolAllocation.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = m.CreatorProtocolRewardAllocation.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = m.CreatorVotingRewardAllocation.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = m.RewardPoolCurationMaxAlloc.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = m.InitialRewardPool.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = len(m.StakeDenom)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	return n
}

func sovCurating(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCurating(x uint64) (n int) {
	return sovCurating(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Post) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Post: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Post: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorID", wireType)
			}
			m.VendorID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VendorID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PostID = append(m.PostID[:0], dAtA[iNdEx:postIndex]...)
			if m.PostID == nil {
				m.PostID = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BodyHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BodyHash = append(m.BodyHash[:0], dAtA[iNdEx:postIndex]...)
			if m.BodyHash == nil {
				m.BodyHash = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CuratingEndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CuratingEndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCurating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Upvote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Upvote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Upvote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorID", wireType)
			}
			m.VendorID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VendorID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PostID = append(m.PostID[:0], dAtA[iNdEx:postIndex]...)
			if m.PostID == nil {
				m.PostID = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Curator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Curator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VoteAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CuratedTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CuratedTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCurating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VPPair) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VPPair: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VPPair: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorID", wireType)
			}
			m.VendorID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VendorID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PostID = append(m.PostID[:0], dAtA[iNdEx:postIndex]...)
			if m.PostID == nil {
				m.PostID = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCurating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VPPairs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VPPairs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VPPairs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pairs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pairs = append(m.Pairs, VPPair{})
			if err := m.Pairs[len(m.Pairs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCurating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurationWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.CurationWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VoteAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxNumVotes", wireType)
			}
			m.MaxNumVotes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxNumVotes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxVendors", wireType)
			}
			m.MaxVendors = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxVendors |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardPoolAllocation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RewardPoolAllocation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorProtocolRewardAllocation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CreatorProtocolRewardAllocation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorVotingRewardAllocation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CreatorVotingRewardAllocation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardPoolCurationMaxAlloc", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RewardPoolCurationMaxAlloc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialRewardPool", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialRewardPool.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakeDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCurating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCurating(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCurating
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCurating
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCurating
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCurating        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCurating          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCurating = fmt.Errorf("proto: unexpected end of group")
)
