// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stargaze/curating/v1beta1/curating.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	VendorID        uint32     `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id" yaml:"vendor_id"`
	PostID          PostID     `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3,customtype=PostID" json:"post_id" yaml:"post_id"`
	Creator         string     `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty" yaml:"creator"`
	RewardAccount   string     `protobuf:"bytes,4,opt,name=reward_account,json=rewardAccount,proto3" json:"reward_account,omitempty" yaml:"reward_account"`
	BodyHash        BodyHash   `protobuf:"bytes,5,opt,name=body_hash,json=bodyHash,proto3,customtype=BodyHash" json:"body_hash" yaml:"body_hash"`
	Body            string     `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty" yaml:"body"`
	CuratingEndTime time.Time  `protobuf:"bytes,7,opt,name=curating_end_time,json=curatingEndTime,proto3,stdtime" json:"curating_end_time" yaml:"curating_end_time"`
	TotalVotes      uint64     `protobuf:"varint,8,opt,name=total_votes,json=totalVotes,proto3" json:"total_votes" yaml:"total_votes"`
	TotalVoters     uint64     `protobuf:"varint,9,opt,name=total_voters,json=totalVoters,proto3" json:"total_voters" yaml:"total_voters"`
	TotalAmount     types.Coin `protobuf:"bytes,10,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount" yaml:"total_amount"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_f99a255b9313441e, []int{0}
}
func (m *Post) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Post.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return m.Size()
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetVendorID() uint32 {
	if m != nil {
		return m.VendorID
	}
	return 0
}

func (m *Post) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Post) GetRewardAccount() string {
	if m != nil {
		return m.RewardAccount
	}
	return ""
}

func (m *Post) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Post) GetCuratingEndTime() time.Time {
	if m != nil {
		return m.CuratingEndTime
	}
	return time.Time{}
}

func (m *Post) GetTotalVotes() uint64 {
	if m != nil {
		return m.TotalVotes
	}
	return 0
}

func (m *Post) GetTotalVoters() uint64 {
	if m != nil {
		return m.TotalVoters
	}
	return 0
}

func (m *Post) GetTotalAmount() types.Coin {
	if m != nil {
		return m.TotalAmount
	}
	return types.Coin{}
}

type Upvote struct {
	VendorID      uint32     `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id" yaml:"vendor_id"`
	PostID        PostID     `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3,customtype=PostID" json:"post_id" yaml:"post_id"`
	Curator       string     `protobuf:"bytes,3,opt,name=curator,proto3" json:"curator,omitempty" yaml:"curator"`
	RewardAccount string     `protobuf:"bytes,4,opt,name=reward_account,json=rewardAccount,proto3" json:"reward_account,omitempty" yaml:"reward_account"`
	VoteAmount    types.Coin `protobuf:"bytes,5,opt,name=vote_amount,json=voteAmount,proto3" json:"vote_amount"`
	CuratedTime   time.Time  `protobuf:"bytes,6,opt,name=curated_time,json=curatedTime,proto3,stdtime" json:"curated_time" yaml:"curated_time"`
}

func (m *Upvote) Reset()         { *m = Upvote{} }
func (m *Upvote) String() string { return proto.CompactTextString(m) }
func (*Upvote) ProtoMessage()    {}
func (*Upvote) Descriptor() ([]byte, []int) {
	return fileDescriptor_f99a255b9313441e, []int{1}
}
func (m *Upvote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Upvote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Upvote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Upvote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Upvote.Merge(m, src)
}
func (m *Upvote) XXX_Size() int {
	return m.Size()
}
func (m *Upvote) XXX_DiscardUnknown() {
	xxx_messageInfo_Upvote.DiscardUnknown(m)
}

var xxx_messageInfo_Upvote proto.InternalMessageInfo

func (m *Upvote) GetVendorID() uint32 {
	if m != nil {
		return m.VendorID
	}
	return 0
}

func (m *Upvote) GetCurator() string {
	if m != nil {
		return m.Curator
	}
	return ""
}

func (m *Upvote) GetRewardAccount() string {
	if m != nil {
		return m.RewardAccount
	}
	return ""
}

func (m *Upvote) GetVoteAmount() types.Coin {
	if m != nil {
		return m.VoteAmount
	}
	return types.Coin{}
}

func (m *Upvote) GetCuratedTime() time.Time {
	if m != nil {
		return m.CuratedTime
	}
	return time.Time{}
}

// VPPair is struct that just has a vendor_id, post_id pair with no other data.
// It is intended to be used as a marshalable pointer. For example, a VPPair can
// be used to construct the key to getting an Upvote from state.
type VPPair struct {
	VendorID uint32 `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id" yaml:"vendor_id"`
	PostID   PostID `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3,customtype=PostID" json:"post_id" yaml:"post_id"`
}

func (m *VPPair) Reset()         { *m = VPPair{} }
func (m *VPPair) String() string { return proto.CompactTextString(m) }
func (*VPPair) ProtoMessage()    {}
func (*VPPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_f99a255b9313441e, []int{2}
}
func (m *VPPair) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VPPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VPPair.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VPPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPPair.Merge(m, src)
}
func (m *VPPair) XXX_Size() int {
	return m.Size()
}
func (m *VPPair) XXX_DiscardUnknown() {
	xxx_messageInfo_VPPair.DiscardUnknown(m)
}

var xxx_messageInfo_VPPair proto.InternalMessageInfo

func (m *VPPair) GetVendorID() uint32 {
	if m != nil {
		return m.VendorID
	}
	return 0
}

// VPPairs defines an array of VPPair objects.
type VPPairs struct {
	Pairs []VPPair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs"`
}

func (m *VPPairs) Reset()         { *m = VPPairs{} }
func (m *VPPairs) String() string { return proto.CompactTextString(m) }
func (*VPPairs) ProtoMessage()    {}
func (*VPPairs) Descriptor() ([]byte, []int) {
	return fileDescriptor_f99a255b9313441e, []int{3}
}
func (m *VPPairs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VPPairs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VPPairs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VPPairs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPPairs.Merge(m, src)
}
func (m *VPPairs) XXX_Size() int {
	return m.Size()
}
func (m *VPPairs) XXX_DiscardUnknown() {
	xxx_messageInfo_VPPairs.DiscardUnknown(m)
}

var xxx_messageInfo_VPPairs proto.InternalMessageInfo

func (m *VPPairs) GetPairs() []VPPair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type Params struct {
	CurationWindow             time.Duration                          `protobuf:"bytes,1,opt,name=curation_window,json=curationWindow,proto3,stdduration" json:"curation_window" yaml:"curation_window"`
	VoteAmount                 types.Coin                             `protobuf:"bytes,2,opt,name=vote_amount,json=voteAmount,proto3" json:"vote_amount" yaml:"vote_amount"`
	MaxNumVotes                uint32                                 `protobuf:"varint,3,opt,name=max_num_votes,json=maxNumVotes,proto3" json:"max_num_votes" yaml:"max_num_votes"`
	MaxVendors                 uint32                                 `protobuf:"varint,4,opt,name=max_vendors,json=maxVendors,proto3" json:"max_vendors" yaml:"max_vendors"`
	RewardPoolAllocation       github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,5,opt,name=reward_pool_allocation,json=rewardPoolAllocation,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"reward_pool_allocation" yaml:"reward_pool_allocation"`
	RewardPoolCurationMaxAlloc github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,8,opt,name=reward_pool_curation_max_alloc,json=rewardPoolCurationMaxAlloc,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"reward_pool_curation_max_alloc,omitempty" yaml:"reward_pool_curation_max_alloc"`
	InitialRewardPool          types.Coin                             `protobuf:"bytes,9,opt,name=initial_reward_pool,json=initialRewardPool,proto3" json:"initial_reward_pool" yaml:"initial_reward_pool"`
	StakeDenom                 string                                 `protobuf:"bytes,10,opt,name=stake_denom,json=stakeDenom,proto3" json:"stake_denom" yaml:"stake_denom"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_f99a255b9313441e, []int{4}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetCurationWindow() time.Duration {
	if m != nil {
		return m.CurationWindow
	}
	return 0
}

func (m *Params) GetVoteAmount() types.Coin {
	if m != nil {
		return m.VoteAmount
	}
	return types.Coin{}
}

func (m *Params) GetMaxNumVotes() uint32 {
	if m != nil {
		return m.MaxNumVotes
	}
	return 0
}

func (m *Params) GetMaxVendors() uint32 {
	if m != nil {
		return m.MaxVendors
	}
	return 0
}

func (m *Params) GetInitialRewardPool() types.Coin {
	if m != nil {
		return m.InitialRewardPool
	}
	return types.Coin{}
}

func (m *Params) GetStakeDenom() string {
	if m != nil {
		return m.StakeDenom
	}
	return ""
}

func init() {
	proto.RegisterType((*Post)(nil), "stargaze.curating.v1beta1.Post")
	proto.RegisterType((*Upvote)(nil), "stargaze.curating.v1beta1.Upvote")
	proto.RegisterType((*VPPair)(nil), "stargaze.curating.v1beta1.VPPair")
	proto.RegisterType((*VPPairs)(nil), "stargaze.curating.v1beta1.VPPairs")
	proto.RegisterType((*Params)(nil), "stargaze.curating.v1beta1.Params")
}

func init() {
	proto.RegisterFile("stargaze/curating/v1beta1/curating.proto", fileDescriptor_f99a255b9313441e)
}

var fileDescriptor_f99a255b9313441e = []byte{
	// 1062 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4d, 0x6f, 0x1b, 0xc5,
	0x1b, 0xcf, 0x36, 0x8e, 0x63, 0x8f, 0x9b, 0xf4, 0xdf, 0x4d, 0xfe, 0x95, 0x13, 0x09, 0x4f, 0x18,
	0x28, 0x72, 0xa5, 0x66, 0xad, 0x36, 0x02, 0x89, 0x48, 0x95, 0x1a, 0x37, 0xa0, 0x06, 0x29, 0x25,
	0x5a, 0x85, 0x20, 0x7a, 0x60, 0x35, 0xf6, 0x4e, 0x9d, 0x55, 0xbd, 0x3b, 0xd6, 0xce, 0x38, 0x71,
	0xb8, 0x02, 0xf7, 0x9e, 0x50, 0x8e, 0xf9, 0x00, 0x88, 0x23, 0x9f, 0x21, 0xc7, 0x1e, 0x11, 0x87,
	0x01, 0x39, 0x17, 0x94, 0xe3, 0x7e, 0x02, 0x34, 0x2f, 0xfb, 0x62, 0x37, 0x34, 0x42, 0xe2, 0xd0,
	0x93, 0x67, 0x7f, 0xcf, 0xf3, 0xfb, 0xcd, 0x33, 0xcf, 0xcb, 0x8c, 0x41, 0x93, 0x71, 0x1c, 0xf7,
	0xf0, 0x77, 0xa4, 0xd5, 0x1d, 0xc6, 0x98, 0x07, 0x51, 0xaf, 0x75, 0xf4, 0xa0, 0x43, 0x38, 0x7e,
	0x90, 0x01, 0xce, 0x20, 0xa6, 0x9c, 0xda, 0x2b, 0xa9, 0xa7, 0x93, 0x19, 0x8c, 0xe7, 0xea, 0x72,
	0x8f, 0xf6, 0xa8, 0xf2, 0x6a, 0xc9, 0x95, 0x26, 0xac, 0x36, 0xba, 0x94, 0x85, 0x94, 0xb5, 0x3a,
	0x98, 0x91, 0x5c, 0x94, 0x06, 0x91, 0xb1, 0xc3, 0x1e, 0xa5, 0xbd, 0x3e, 0x69, 0xa9, 0xaf, 0xce,
	0xf0, 0x45, 0x8b, 0x07, 0x21, 0x61, 0x1c, 0x87, 0x83, 0x54, 0x60, 0xda, 0xc1, 0x57, 0x1b, 0x53,
	0x23, 0x80, 0x7e, 0x2e, 0x83, 0xd2, 0x1e, 0x65, 0xdc, 0xfe, 0x02, 0x54, 0x8f, 0x48, 0xe4, 0xd3,
	0xd8, 0x0b, 0xfc, 0xba, 0xb5, 0x66, 0x35, 0x17, 0xda, 0xeb, 0x63, 0x01, 0x2b, 0x07, 0x0a, 0xdc,
	0xd9, 0xbe, 0x14, 0x30, 0x77, 0x48, 0x04, 0xfc, 0xdf, 0x09, 0x0e, 0xfb, 0x9b, 0x28, 0x83, 0x90,
	0x5b, 0xd1, 0xeb, 0x1d, 0xdf, 0x7e, 0x06, 0xe6, 0x07, 0x94, 0x71, 0xa9, 0x74, 0x63, 0xcd, 0x6a,
	0x56, 0xdb, 0x1f, 0x9f, 0x0b, 0x38, 0xf3, 0xbb, 0x80, 0x65, 0xb9, 0xd5, 0xce, 0xf6, 0x38, 0x5b,
	0x5d, 0x0a, 0x98, 0xba, 0x26, 0x02, 0x2e, 0x6a, 0x4d, 0x03, 0x20, 0xb7, 0x2c, 0x57, 0x3b, 0xbe,
	0x7d, 0x1f, 0xcc, 0x77, 0x63, 0x82, 0x39, 0x8d, 0xeb, 0xb3, 0x4a, 0xcf, 0xce, 0x9d, 0x8d, 0x01,
	0xb9, 0xa9, 0x8b, 0xfd, 0x18, 0x2c, 0xc6, 0xe4, 0x18, 0xc7, 0xbe, 0x87, 0xbb, 0x5d, 0x3a, 0x8c,
	0x78, 0xbd, 0xa4, 0x48, 0x2b, 0x89, 0x80, 0xff, 0xd7, 0xa4, 0x49, 0x3b, 0x72, 0x17, 0x34, 0xb0,
	0xa5, 0xbf, 0xed, 0xe7, 0xa0, 0xda, 0xa1, 0xfe, 0x89, 0x77, 0x88, 0xd9, 0x61, 0x7d, 0x4e, 0x91,
	0x1f, 0x99, 0x13, 0x54, 0xda, 0xd4, 0x3f, 0x79, 0x8a, 0xd9, 0xe1, 0xb8, 0xb0, 0x96, 0xb9, 0xc9,
	0x08, 0x79, 0x6e, 0x32, 0x08, 0xb9, 0x95, 0x8e, 0x71, 0xb5, 0x3f, 0x00, 0x25, 0xb9, 0xae, 0x97,
	0x95, 0xec, 0xad, 0x44, 0xc0, 0x5a, 0xee, 0x8d, 0x5c, 0x65, 0xb4, 0xfb, 0xe0, 0x76, 0xda, 0x20,
	0x1e, 0x89, 0x7c, 0x4f, 0x56, 0xb5, 0x3e, 0xbf, 0x66, 0x35, 0x6b, 0x0f, 0x57, 0x1d, 0x5d, 0x51,
	0x27, 0xad, 0xa8, 0xb3, 0x9f, 0x96, 0xbc, 0xfd, 0xa1, 0x0c, 0x32, 0x11, 0xb0, 0x6e, 0x52, 0x33,
	0x2d, 0x81, 0x5e, 0xfd, 0x01, 0x2d, 0xf7, 0x56, 0x8a, 0x7f, 0x16, 0xf9, 0x92, 0x6b, 0xef, 0x83,
	0x1a, 0xa7, 0x1c, 0xf7, 0xbd, 0x23, 0xca, 0x09, 0xab, 0x57, 0xd6, 0xac, 0x66, 0xa9, 0xbd, 0x31,
	0x16, 0x10, 0xec, 0x4b, 0xf8, 0x40, 0xa2, 0x97, 0x02, 0x16, 0x9d, 0x12, 0x01, 0x6d, 0xbd, 0x49,
	0x01, 0x44, 0x2e, 0xe0, 0x19, 0xc1, 0xfe, 0x06, 0xdc, 0xcc, 0x6d, 0x31, 0xab, 0x57, 0x95, 0xec,
	0x27, 0x63, 0x01, 0x6b, 0x99, 0x6c, 0x2c, 0x75, 0x27, 0xdc, 0x12, 0x01, 0x97, 0xa6, 0x85, 0x63,
	0x86, 0xdc, 0x1a, 0xcf, 0x39, 0xf6, 0x28, 0x95, 0xc6, 0xa1, 0xaa, 0x2f, 0x50, 0x99, 0x59, 0x71,
	0xf4, 0xb0, 0x38, 0x72, 0x58, 0xd2, 0xb9, 0x72, 0x9e, 0xd0, 0x20, 0x6a, 0x6f, 0xca, 0xc4, 0x64,
	0x3b, 0x6f, 0x29, 0x56, 0xbe, 0xb3, 0x56, 0x99, 0xde, 0x59, 0xa3, 0xe9, 0xce, 0x9a, 0x83, 0x7e,
	0x9d, 0x05, 0xe5, 0xaf, 0x06, 0x32, 0xa8, 0x77, 0x7e, 0x60, 0x64, 0x91, 0xaf, 0x1c, 0x18, 0x6d,
	0x90, 0x03, 0xa3, 0x57, 0xff, 0xc1, 0xc0, 0x3c, 0x06, 0x35, 0x99, 0x93, 0xb4, 0x1e, 0x73, 0xd7,
	0xd5, 0xa3, 0x24, 0x8f, 0xe7, 0x02, 0xc9, 0xd1, 0x89, 0xb5, 0xbf, 0x05, 0x37, 0x55, 0x38, 0xc4,
	0x34, 0x7b, 0xf9, 0xda, 0x66, 0x87, 0xa6, 0xd9, 0x97, 0x0a, 0xc7, 0x22, 0xc5, 0x3e, 0xaf, 0x19,
	0x48, 0x52, 0xd0, 0x2f, 0x16, 0x28, 0x1f, 0xec, 0xed, 0xe1, 0x20, 0x7e, 0x97, 0x0b, 0xb7, 0x59,
	0x39, 0x3d, 0x83, 0xd6, 0x5f, 0x67, 0xd0, 0x42, 0x4f, 0xc1, 0xbc, 0x8e, 0x97, 0xd9, 0x8f, 0xc0,
	0xdc, 0x40, 0x2e, 0xea, 0xd6, 0xda, 0x6c, 0xb3, 0xf6, 0xf0, 0x7d, 0xe7, 0x1f, 0x5f, 0x11, 0x47,
	0x53, 0x4c, 0x7e, 0x35, 0x0b, 0xfd, 0x34, 0x0f, 0xca, 0x7b, 0x38, 0xc6, 0x21, 0xb3, 0x5f, 0x00,
	0x33, 0xfc, 0x34, 0xf2, 0x8e, 0x83, 0xc8, 0xa7, 0xc7, 0x2a, 0x01, 0xb2, 0x56, 0xd3, 0x89, 0xde,
	0x36, 0x7e, 0x6d, 0x64, 0xf2, 0x7c, 0xa7, 0x78, 0xa9, 0x64, 0x7c, 0x74, 0x2a, 0x53, 0xbd, 0x98,
	0xa2, 0x5f, 0x2b, 0xd0, 0x26, 0x93, 0xfd, 0x70, 0xe3, 0xba, 0x7e, 0xb8, 0x27, 0xf7, 0x90, 0x57,
	0x4c, 0x81, 0x95, 0x5f, 0x31, 0x05, 0x10, 0x4d, 0x34, 0xcd, 0x2e, 0x58, 0x08, 0xf1, 0xc8, 0x8b,
	0x86, 0xa1, 0xb9, 0xba, 0x66, 0x55, 0x35, 0xef, 0x5d, 0x0a, 0x38, 0x69, 0x48, 0x04, 0x5c, 0xd6,
	0x5a, 0x13, 0x30, 0x72, 0x6b, 0x21, 0x1e, 0x3d, 0x1b, 0x86, 0xfa, 0xc6, 0xfa, 0x1c, 0xc8, 0x4f,
	0x4f, 0x17, 0x97, 0xa9, 0x21, 0x58, 0x68, 0xdf, 0x95, 0x61, 0x15, 0xe0, 0x3c, 0xac, 0x02, 0x88,
	0x5c, 0x10, 0xe2, 0x91, 0x6e, 0x20, 0x66, 0xff, 0x68, 0x81, 0x3b, 0x66, 0x60, 0x06, 0x94, 0xf6,
	0x3d, 0xdc, 0xef, 0xd3, 0xae, 0x4a, 0x8f, 0x79, 0x4c, 0xbe, 0x34, 0x4d, 0xf2, 0x51, 0x2f, 0xe0,
	0x87, 0xc3, 0x8e, 0xd3, 0xa5, 0x61, 0xcb, 0x3c, 0xf4, 0xfa, 0x67, 0x9d, 0xf9, 0x2f, 0x5b, 0xfc,
	0x64, 0x40, 0x98, 0xb3, 0x4d, 0xba, 0x89, 0x80, 0xef, 0x4d, 0x8c, 0xe1, 0x94, 0x2a, 0x72, 0x97,
	0xb5, 0x61, 0x8f, 0xd2, 0xfe, 0x56, 0x06, 0xdb, 0xe7, 0x16, 0x68, 0x14, 0x19, 0x59, 0xe9, 0x64,
	0xe4, 0x8a, 0xae, 0xee, 0xfa, 0x6a, 0xfb, 0x7b, 0xeb, 0xdf, 0x05, 0x74, 0x29, 0x60, 0xf3, 0xed,
	0xc2, 0xf7, 0x69, 0x18, 0x70, 0x12, 0x0e, 0xf8, 0x49, 0x22, 0xe0, 0xdd, 0x37, 0x83, 0x7f, 0x93,
	0x81, 0xdc, 0xd5, 0xfc, 0x10, 0x4f, 0x8c, 0x79, 0x17, 0x8f, 0xd4, 0x79, 0xec, 0x1f, 0x2c, 0xb0,
	0x14, 0x44, 0x01, 0x0f, 0x70, 0xdf, 0x2b, 0xe8, 0xa8, 0x47, 0xe5, 0xad, 0x9d, 0xf5, 0xa9, 0xe9,
	0xac, 0xab, 0xd8, 0x89, 0x80, 0xab, 0x3a, 0xb4, 0x2b, 0x8c, 0xc8, 0xbd, 0x6d, 0x50, 0x37, 0x0b,
	0x4b, 0x76, 0x08, 0xe3, 0xf8, 0x25, 0xf1, 0x7c, 0x12, 0xd1, 0x50, 0xbd, 0x3b, 0x55, 0xdd, 0x21,
	0x05, 0x38, 0xef, 0x90, 0x02, 0x88, 0x5c, 0xa0, 0xbe, 0xb6, 0xe5, 0xc7, 0x66, 0xe9, 0xf4, 0x0c,
	0xce, 0xb4, 0x77, 0xcf, 0xc7, 0x0d, 0xeb, 0xf5, 0xb8, 0x61, 0xfd, 0x39, 0x6e, 0x58, 0xaf, 0x2e,
	0x1a, 0x33, 0xaf, 0x2f, 0x1a, 0x33, 0xbf, 0x5d, 0x34, 0x66, 0x9e, 0x6f, 0x14, 0xea, 0x30, 0x18,
	0x76, 0xfa, 0x41, 0x77, 0x1d, 0x1f, 0x13, 0x46, 0x43, 0xd2, 0xca, 0xfe, 0x6b, 0x8e, 0xf2, 0x7f,
	0x9b, 0xaa, 0x30, 0x9d, 0xb2, 0x9a, 0xdd, 0x8d, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x92, 0xc8,
	0x85, 0x13, 0x8f, 0x0a, 0x00, 0x00,
}

func (this *VPPair) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VPPair)
	if !ok {
		that2, ok := that.(VPPair)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.VendorID != that1.VendorID {
		return false
	}
	if !this.PostID.Equal(that1.PostID) {
		return false
	}
	return true
}
func (m *Post) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Post) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Post) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TotalAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	if m.TotalVoters != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.TotalVoters))
		i--
		dAtA[i] = 0x48
	}
	if m.TotalVotes != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.TotalVotes))
		i--
		dAtA[i] = 0x40
	}
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CuratingEndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CuratingEndTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintCurating(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x3a
	if len(m.Body) > 0 {
		i -= len(m.Body)
		copy(dAtA[i:], m.Body)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.Body)))
		i--
		dAtA[i] = 0x32
	}
	{
		size := m.BodyHash.Size()
		i -= size
		if _, err := m.BodyHash.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.RewardAccount) > 0 {
		i -= len(m.RewardAccount)
		copy(dAtA[i:], m.RewardAccount)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.RewardAccount)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.PostID.Size()
		i -= size
		if _, err := m.PostID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.VendorID != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.VendorID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Upvote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Upvote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Upvote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CuratedTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CuratedTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintCurating(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x32
	{
		size, err := m.VoteAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.RewardAccount) > 0 {
		i -= len(m.RewardAccount)
		copy(dAtA[i:], m.RewardAccount)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.RewardAccount)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Curator) > 0 {
		i -= len(m.Curator)
		copy(dAtA[i:], m.Curator)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.Curator)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.PostID.Size()
		i -= size
		if _, err := m.PostID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.VendorID != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.VendorID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *VPPair) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VPPair) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VPPair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.PostID.Size()
		i -= size
		if _, err := m.PostID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.VendorID != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.VendorID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *VPPairs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VPPairs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VPPairs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Pairs) > 0 {
		for iNdEx := len(m.Pairs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pairs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCurating(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StakeDenom) > 0 {
		i -= len(m.StakeDenom)
		copy(dAtA[i:], m.StakeDenom)
		i = encodeVarintCurating(dAtA, i, uint64(len(m.StakeDenom)))
		i--
		dAtA[i] = 0x52
	}
	{
		size, err := m.InitialRewardPool.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.RewardPoolCurationMaxAlloc.Size()
		i -= size
		if _, err := m.RewardPoolCurationMaxAlloc.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.RewardPoolAllocation.Size()
		i -= size
		if _, err := m.RewardPoolAllocation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.MaxVendors != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.MaxVendors))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxNumVotes != 0 {
		i = encodeVarintCurating(dAtA, i, uint64(m.MaxNumVotes))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.VoteAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCurating(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	n7, err7 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.CurationWindow, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.CurationWindow):])
	if err7 != nil {
		return 0, err7
	}
	i -= n7
	i = encodeVarintCurating(dAtA, i, uint64(n7))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintCurating(dAtA []byte, offset int, v uint64) int {
	offset -= sovCurating(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Post) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VendorID != 0 {
		n += 1 + sovCurating(uint64(m.VendorID))
	}
	l = m.PostID.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = len(m.RewardAccount)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = m.BodyHash.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = len(m.Body)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CuratingEndTime)
	n += 1 + l + sovCurating(uint64(l))
	if m.TotalVotes != 0 {
		n += 1 + sovCurating(uint64(m.TotalVotes))
	}
	if m.TotalVoters != 0 {
		n += 1 + sovCurating(uint64(m.TotalVoters))
	}
	l = m.TotalAmount.Size()
	n += 1 + l + sovCurating(uint64(l))
	return n
}

func (m *Upvote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VendorID != 0 {
		n += 1 + sovCurating(uint64(m.VendorID))
	}
	l = m.PostID.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = len(m.Curator)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = len(m.RewardAccount)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	l = m.VoteAmount.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CuratedTime)
	n += 1 + l + sovCurating(uint64(l))
	return n
}

func (m *VPPair) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VendorID != 0 {
		n += 1 + sovCurating(uint64(m.VendorID))
	}
	l = m.PostID.Size()
	n += 1 + l + sovCurating(uint64(l))
	return n
}

func (m *VPPairs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Pairs) > 0 {
		for _, e := range m.Pairs {
			l = e.Size()
			n += 1 + l + sovCurating(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.CurationWindow)
	n += 1 + l + sovCurating(uint64(l))
	l = m.VoteAmount.Size()
	n += 1 + l + sovCurating(uint64(l))
	if m.MaxNumVotes != 0 {
		n += 1 + sovCurating(uint64(m.MaxNumVotes))
	}
	if m.MaxVendors != 0 {
		n += 1 + sovCurating(uint64(m.MaxVendors))
	}
	l = m.RewardPoolAllocation.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = m.RewardPoolCurationMaxAlloc.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = m.InitialRewardPool.Size()
	n += 1 + l + sovCurating(uint64(l))
	l = len(m.StakeDenom)
	if l > 0 {
		n += 1 + l + sovCurating(uint64(l))
	}
	return n
}

func sovCurating(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCurating(x uint64) (n int) {
	return sovCurating(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Post) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Post: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Post: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorID", wireType)
			}
			m.VendorID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VendorID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PostID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BodyHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BodyHash.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Body", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Body = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CuratingEndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CuratingEndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalVotes", wireType)
			}
			m.TotalVotes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalVotes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalVoters", wireType)
			}
			m.TotalVoters = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalVoters |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCurating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Upvote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Upvote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Upvote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorID", wireType)
			}
			m.VendorID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VendorID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PostID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Curator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Curator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VoteAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CuratedTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CuratedTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCurating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VPPair) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VPPair: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VPPair: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorID", wireType)
			}
			m.VendorID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VendorID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PostID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCurating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VPPairs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VPPairs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VPPairs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pairs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pairs = append(m.Pairs, VPPair{})
			if err := m.Pairs[len(m.Pairs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCurating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurationWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.CurationWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VoteAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxNumVotes", wireType)
			}
			m.MaxNumVotes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxNumVotes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxVendors", wireType)
			}
			m.MaxVendors = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxVendors |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardPoolAllocation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RewardPoolAllocation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardPoolCurationMaxAlloc", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RewardPoolCurationMaxAlloc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialRewardPool", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialRewardPool.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCurating
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCurating
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakeDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCurating(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCurating
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCurating(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCurating
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCurating
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCurating
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCurating
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCurating
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCurating        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCurating          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCurating = fmt.Errorf("proto: unexpected end of group")
)
