// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stakebird/curating/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	Params        Params                                   `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	RewardPool    github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=reward_pool,json=rewardPool,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"reward_pool"`
	Posts         Posts                                    `protobuf:"bytes,3,rep,name=posts,proto3,castrepeated=Posts" json:"posts"`
	Upvotes       Upvotes                                  `protobuf:"bytes,4,rep,name=upvotes,proto3,castrepeated=Upvotes" json:"upvotes"`
	CuratingQueue CuratingQueue                            `protobuf:"bytes,5,rep,name=curating_queue,json=curatingQueue,proto3,castrepeated=CuratingQueue" json:"curating_queue"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebb830c4f4aa37c6, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetRewardPool() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.RewardPool
	}
	return nil
}

func (m *GenesisState) GetPosts() Posts {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *GenesisState) GetUpvotes() Upvotes {
	if m != nil {
		return m.Upvotes
	}
	return nil
}

func (m *GenesisState) GetCuratingQueue() CuratingQueue {
	if m != nil {
		return m.CuratingQueue
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "stakebird.curating.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("stakebird/curating/v1beta1/genesis.proto", fileDescriptor_ebb830c4f4aa37c6)
}

var fileDescriptor_ebb830c4f4aa37c6 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x8e, 0xd3, 0x30,
	0x14, 0x86, 0x13, 0x3a, 0x9d, 0x91, 0x5c, 0x0a, 0x52, 0x04, 0x52, 0xe8, 0x22, 0x53, 0x0d, 0x9b,
	0xb0, 0x18, 0x9b, 0x19, 0x38, 0x00, 0x4a, 0x85, 0x58, 0x81, 0x42, 0x10, 0x2c, 0xd8, 0x54, 0x4e,
	0x6a, 0x05, 0xab, 0x49, 0x5e, 0xc8, 0x73, 0x5a, 0xb8, 0x05, 0xe7, 0xe0, 0x02, 0x5c, 0xa1, 0xcb,
	0x2e, 0x59, 0x01, 0x6a, 0x2f, 0x82, 0xe2, 0xb8, 0x69, 0x37, 0x93, 0x55, 0xf2, 0xe4, 0xff, 0xff,
	0xfe, 0xdf, 0xd6, 0x23, 0x3e, 0x2a, 0xbe, 0x14, 0xb1, 0xac, 0x16, 0x2c, 0xa9, 0x2b, 0xae, 0x64,
	0x91, 0xb2, 0xd5, 0x4d, 0x2c, 0x14, 0xbf, 0x61, 0xa9, 0x28, 0x04, 0x4a, 0xa4, 0x65, 0x05, 0x0a,
	0x9c, 0x49, 0xa7, 0xa4, 0x07, 0x25, 0x35, 0xca, 0xc9, 0xa3, 0x14, 0x52, 0xd0, 0x32, 0xd6, 0xfc,
	0xb5, 0x8e, 0x89, 0x97, 0x00, 0xe6, 0x80, 0x2c, 0xe6, 0x28, 0x3a, 0x68, 0x02, 0xb2, 0x30, 0xe7,
	0xcf, 0x7a, 0xb2, 0xbb, 0x08, 0x2d, 0xbd, 0xfa, 0x35, 0x20, 0xf7, 0xdf, 0xb4, 0x75, 0x3e, 0x28,
	0xae, 0x84, 0xf3, 0x8a, 0x9c, 0x97, 0xbc, 0xe2, 0x39, 0xba, 0xf6, 0xd4, 0xf6, 0x47, 0xb7, 0x57,
	0xf4, 0xee, 0x7a, 0x34, 0xd4, 0xca, 0xe0, 0x6c, 0xf3, 0xe7, 0xd2, 0x8a, 0x8c, 0xcf, 0xc9, 0xc8,
	0xa8, 0x12, 0x6b, 0x5e, 0x2d, 0xe6, 0x25, 0x40, 0xe6, 0xde, 0x9b, 0x0e, 0xfc, 0xd1, 0xed, 0x13,
	0xda, 0x76, 0xa6, 0x4d, 0xe7, 0xce, 0x3f, 0x03, 0x59, 0x04, 0xcf, 0x1b, 0xf7, 0xcf, 0xbf, 0x97,
	0x7e, 0x2a, 0xd5, 0x97, 0x3a, 0xa6, 0x09, 0xe4, 0xcc, 0x5c, 0xb0, 0xfd, 0x5c, 0xe3, 0x62, 0xc9,
	0xd4, 0xf7, 0x52, 0xa0, 0x36, 0x60, 0x44, 0x5a, 0x7e, 0x08, 0x90, 0x39, 0xaf, 0xc9, 0xb0, 0x04,
	0x54, 0xe8, 0x0e, 0x74, 0xce, 0xb4, 0xb7, 0x2e, 0xa0, 0x0a, 0xc6, 0x26, 0x6e, 0xd8, 0x4c, 0x18,
	0xb5, 0x6e, 0xe7, 0x2d, 0xb9, 0xa8, 0xcb, 0x15, 0x28, 0x81, 0xee, 0x99, 0x06, 0xf5, 0xde, 0xfb,
	0xa3, 0x96, 0x06, 0x0f, 0x0d, 0xea, 0xa2, 0x9d, 0x31, 0x3a, 0x30, 0x1c, 0x4e, 0x1e, 0x1c, 0x4c,
	0xf3, 0xaf, 0xb5, 0xa8, 0x85, 0x3b, 0xd4, 0xd4, 0xa7, 0x7d, 0xd4, 0x4f, 0x61, 0xc8, 0x65, 0x85,
	0xc1, 0x63, 0x83, 0x1d, 0xcf, 0x8c, 0xe2, 0x7d, 0x43, 0x88, 0xc6, 0xc9, 0xe9, 0x18, 0xbc, 0xdb,
	0xec, 0x3c, 0x7b, 0xbb, 0xf3, 0xec, 0x7f, 0x3b, 0xcf, 0xfe, 0xb1, 0xf7, 0xac, 0xed, 0xde, 0xb3,
	0x7e, 0xef, 0x3d, 0xeb, 0xf3, 0xcb, 0x93, 0x87, 0x2c, 0xeb, 0x38, 0x93, 0xc9, 0x35, 0x5f, 0x0b,
	0x84, 0x5c, 0xb0, 0xe3, 0x62, 0x7c, 0x3b, 0xae, 0x86, 0x7e, 0xda, 0xf8, 0x5c, 0x2f, 0xc4, 0x8b,
	0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x4c, 0x16, 0xb1, 0xb9, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CuratingQueue) > 0 {
		for iNdEx := len(m.CuratingQueue) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CuratingQueue[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Upvotes) > 0 {
		for iNdEx := len(m.Upvotes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Upvotes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Posts) > 0 {
		for iNdEx := len(m.Posts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Posts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.RewardPool) > 0 {
		for iNdEx := len(m.RewardPool) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RewardPool[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.RewardPool) > 0 {
		for _, e := range m.RewardPool {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Posts) > 0 {
		for _, e := range m.Posts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Upvotes) > 0 {
		for _, e := range m.Upvotes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CuratingQueue) > 0 {
		for _, e := range m.CuratingQueue {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardPool", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardPool = append(m.RewardPool, types.Coin{})
			if err := m.RewardPool[len(m.RewardPool)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Posts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Posts = append(m.Posts, Post{})
			if err := m.Posts[len(m.Posts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Upvotes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Upvotes = append(m.Upvotes, Upvote{})
			if err := m.Upvotes[len(m.Upvotes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CuratingQueue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CuratingQueue = append(m.CuratingQueue, VPPairs{})
			if err := m.CuratingQueue[len(m.CuratingQueue)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
