# docker build . -t publicawesome/golang:1.17.0-devtooling -f docker/Dockerfile.go-devtools
FROM golang:1.17.0
RUN apt-get update && \
  apt-get install -y cmake && \
  apt-get -y clean && \
  rm -rf /var/lib/apt/lists/*
